### PR TITLE
shutdown controll-manager if leader election lost

### LINKED ISSUE #3850: tidb-controller-manager reports `Shutting down xxxx controller` and fails to sync the cluster
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

v1.1.10
**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

Install another TiDB Operator in a different namespace with the following configurations:
```
			"clusterScoped": false,
			"operatorImage": "pingcap/tidb-operator:v1.2-nightly",
			"controllerManager": map[string]interface{}{
				"selector": []string{
					"operator-scope=local",
					"operator-name=test",
				},
			},
			"scheduler": map[string]interface{}{
				"create": false,
			},
```
**What did you expect to see?**

**What did you see instead?**
```
 I0312 07:31:14.829702       1 backup_schedule_controller.go:70] Starting backup schedule controller
 I0312 07:31:14.829729       1 backup_schedule_controller.go:78] Shutting down backup schedule controller
 I0312 07:31:15.310602       1 tidb_cluster_controller.go:98] Starting tidbcluster controller
 I0312 07:31:15.310638       1 tidb_cluster_controller.go:106] Shutting down tidbcluster controller
 I0312 07:31:15.718835       1 tidb_monitor_controller.go:65] Starting tidbmonitor controller
 I0312 07:31:15.718864       1 tidb_monitor_controller.go:73] Shutting down tidbmonitor controller
 I0312 07:31:16.441717       1 restore_controller.go:71] Starting restore controller
 I0312 07:31:16.441748       1 restore_controller.go:79] Shutting down restore controller
 I0312 07:31:16.751121       1 tidb_initializer_controller.go:69] Starting tidbinitializer controller
 I0312 07:31:16.751154       1 tidb_initializer_controller.go:77] Shutting down tidbinitializer controller
 I0312 07:31:17.221806       1 dm_cluster_controller.go:90] Starting dmcluster controller
 I0312 07:31:17.221838       1 dm_cluster_controller.go:98] Shutting down dmcluster controller
 I0312 07:31:17.504449       1 backup_controller.go:72] Starting backup controller
 I0312 07:31:17.504477       1 backup_controller.go:80] Shutting down backup controller
 I0312 07:31:19.830530       1 backup_schedule_controller.go:70] Starting backup schedule controller
 I0312 07:31:19.830572       1 backup_schedule_controller.go:78] Shutting down backup schedule controller
 I0312 07:31:20.311436       1 tidb_cluster_controller.go:98] Starting tidbcluster controller
 I0312 07:31:20.311468       1 tidb_cluster_controller.go:106] Shutting down tidbcluster controller
 I0312 07:31:20.718956       1 tidb_monitor_controller.go:65] Starting tidbmonitor controller
 I0312 07:31:20.718987       1 tidb_monitor_controller.go:73] Shutting down tidbmonitor controller
 I0312 07:31:21.442322       1 restore_controller.go:71] Starting restore controller
 I0312 07:31:21.442352       1 restore_controller.go:79] Shutting down restore controller
 I0312 07:31:21.751748       1 tidb_initializer_controller.go:69] Starting tidbinitializer controller
 I0312 07:31:21.751792       1 tidb_initializer_controller.go:77] Shutting down tidbinitializer controller
 I0312 07:31:22.222673       1 dm_cluster_controller.go:90] Starting dmcluster controller
 I0312 07:31:22.222706       1 dm_cluster_controller.go:98] Shutting down dmcluster controller
 I0312 07:31:22.504725       1 backup_controller.go:72] Starting backup controller
 I0312 07:31:22.504753       1 backup_controller.go:80] Shutting down backup controller
 I0312 07:31:24.830849       1 backup_schedule_controller.go:70] Starting backup schedule controller
 I0312 07:31:24.830877       1 backup_schedule_controller.go:78] Shutting down backup schedule controller
```

### PR DESCRIPTION
**Pull request by csuzhangxc**
### What problem does this PR solve?

fix #3850 

### What is changed and how does it work?

- do not retry after leader election lost (remove `wait.Forever`)
- shutdown the HTTP server after leader election lost

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [x] Manual test 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note
```

### CODE REVIEW

File: cmd/controller-manager/main.go [hunk 1]
```diff
@@ -189,14 +190,17 @@ func main() {
 	}
 	onStopped := func() {
 		klog.Error("leader election lost")
+		if err2 := srv.Shutdown(context.Background()); err2 != nil {
```
Comment (july2993) [inline cmd/controller-manager/main.go:193]: what about just panic like before and pass contect.TODO to `leaderelection.RunOrDie`

File: cmd/controller-manager/main.go [hunk 2]
```diff
@@ -217,9 +221,8 @@ func main() {
 				OnStoppedLeading: onStopped,
 			},
 		})
-	}, cliCfg.WaitDuration)
+	}()
 
-	srv := createHTTPServer()
 	sc := make(chan os.Signal, 1)
 	signal.Notify(sc,
 		syscall.SIGHUP,
```
Comment (july2993) [inline cmd/controller-manager/main.go:228]: I don't think we should close  `sc` at line 237, if there are more signal it will panic to push into `sc` before quit

File: cmd/controller-manager/main.go (hunk 1 above)
Comment (csuzhangxc) [reply cmd/controller-manager/main.go:193]: The reason why I removed fatal before was that it didn't work properly. 
If you are interested, you can change to fatal and try.

File: cmd/controller-manager/main.go (hunk 2 above)
Comment (csuzhangxc) [reply cmd/controller-manager/main.go:228]: removed in https://github.com/pingcap/tidb-operator/pull/3890/commits/915fb4e9127396601a9aa45f45a795f8a10e49c6.

File: cmd/controller-manager/main.go (hunk 1 above)
Comment (july2993) [reply cmd/controller-manager/main.go:193]: I am not interested 🐶

I think it was caused by the ctx pass to `RunOrDie` is done before?
and now there are still possible to call srv.Shutdown twice, one in the signal handle func, one is here after reaching end of main func

Comment (DanielZhangQD) [reply cmd/controller-manager/main.go:193]: I think no need to collect the coverage during the leader election lost case, we just need to make sure that the coverage can be collected during the normal shut down.

Comment (csuzhangxc) [reply cmd/controller-manager/main.go]: https://github.com/pingcap/tidb-operator/pull/3890/commits/e5cf3c6fe9751ab2b0bc7cbefc8188bf58ae963c @july2993 do you like it?

Comment (july2993) [reply cmd/controller-manager/main.go]: > I think no need to collect the coverage during the leader election lost case, we just need to make sure that the coverage can be collected during the normal shut down.

yes, because leader election lost is not a normal case, we can treat it as failed to run the test like unit test.

**Review by july2993 — APPROVED** [review]

**Comment by csuzhangxc** [comment]
@DanielZhangQD PTAL

**Review by DanielZhangQD — APPROVED** [review]
LGTM
