### PR TITLE
fix tidb service and tc is updated continuously

### LINKED ISSUE #4007: TiDB service is updated continuously even if without any change to the spec
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

v1.2.0-rc.1
**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

**What did you expect to see?**

**What did you see instead?**
From the log of tidb-controller-manager:
```
I0602 02:55:42.201206       1 service_control.go:87] update Service: [default/t-tidb] successfully, kind: , name: t
I0602 02:55:44.401576       1 service_control.go:87] update Service: [ns1/ns1-tidb] successfully, kind: , name: ns1
I0602 02:55:45.401472       1 service_control.go:87] update Service: [ns2/ns2-tidb] successfully, kind: , name: ns2
I0602 02:55:49.001736       1 service_control.go:87] update Service: [default/t-tidb] successfully, kind: , name: t
I0602 02:55:50.002370       1 service_control.go:87] update Service: [ns1/ns1-tidb] successfully, kind: , name: ns1
I0602 02:55:51.005049       1 service_control.go:87] update Service: [ns2/ns2-tidb] successfully, kind: , name: ns2
I0602 02:55:55.202984       1 service_control.go:87] update Service: [ns1/ns1-tidb] successfully, kind: , name: ns1
I0602 02:55:55.402227       1 service_control.go:87] update Service: [default/t-tidb] successfully, kind: , name: t
I0602 02:55:56.201880       1 service_control.go:87] update Service: [ns2/ns2-tidb] successfully, kind: , name: ns2
```

### PR DESCRIPTION
**Pull request by july2993**
### What problem does this PR solve?

Fix #4007 
### What is changed and how does it work?

remove the useless continuously updated status in tc and keep last apply ann of tidb service
### Code changes

- [ ] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [x] Manual test 
check no "update Service" log after update to this version and no continuously re-sync
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note
Fix tidb service and tc is updated continuously
```

### CODE REVIEW

File: pkg/binlog/binlog.go [hunk 1]
```diff
@@ -95,11 +95,15 @@ type StatusResp struct {
...
-	State       string `json:"state"`
-	MaxCommitTS int64  `json:"maxCommitTS"`
-	UpdateTS    int64  `json:"updateTS"`
+	NodeID string `json:"nodeId"`
+	Host   string `json:"host"`
+	State  string `json:"state"`
+
+	// NB: this fields will be updated continuously.
+	// currently we save the whole `NodeStatus` in status of CRD
+	// to avoid CRD updated and re-sync continuously, we exclude this fields.
```
Comment (DanielZhangQD) [inline pkg/binlog/binlog.go:104]:
```suggestion
	// NB: Currently we save the whole `NodeStatus` in the status of the CR.
	// However, the following fields will be updated continuously.
	// To avoid CR being updated and re-synced continuously, we exclude these fields.
```

File: pkg/controller/equality.go [hunk 2]
```diff
@@ -78,7 +79,15 @@ func ServiceEqual(newSvc, oldSvc *corev1.Service) (bool, error) {
 			klog.Errorf("unmarshal ServiceSpec: [%s/%s]'s applied config failed,error: %v", oldSvc.GetNamespace(), oldSvc.GetName(), err)
 			return false, err
 		}
-		return apiequality.Semantic.DeepEqual(oldSpec, newSvc.Spec), nil
+		equal := apiequality.Semantic.DeepEqual(oldSpec, newSvc.Spec)
+		if !equal {
+			if klog.V(2) {
+				diff := cmp.Diff(oldSpec, newSvc.Spec)
+				klog.V(2).Infof("service spec diff: %s", diff)
```
Comment (DanielZhangQD) [inline pkg/controller/equality.go:86]:
```suggestion
				klog.V(2).Infof("Service spec diff for %s/%s: %s", newSvc.Namespace, newSvc.Name, diff)
```

File: pkg/manager/member/tidb_member_manager.go [hunk 3]
```diff
@@ -313,19 +314,22 @@ func (m *tidbMemberManager) syncTiDBService(tc *v1alpha1.TidbCluster) error {
 		return nil
 	}
 
+	klog.V(2).Infof("spec equal: %v, annotations equal: %v, label equal: %v", equal, annoEqual, labelEqual)
```
Comment (DanielZhangQD) [inline pkg/manager/member/tidb_member_manager.go:317]:
```suggestion
	klog.V(2).Infof("Sync TiSB service %s/%s, spec equal: %v, annotations equal: %v, label equal: %v", newSvc.Namespace, newSvc.Name, equal, annoEqual, labelEqual)
```

Comment (july2993) [reply pkg/manager/member/tidb_member_manager.go:317]: TiSB

**Review by DanielZhangQD — APPROVED** [review]
LGTM

File: pkg/binlog/binlog.go [hunk 4]
```diff
@@ -95,11 +95,15 @@ type StatusResp struct {
...
-	NodeID      string `json:"nodeId"`
-	Host        string `json:"host"`
-	State       string `json:"state"`
-	MaxCommitTS int64  `json:"maxCommitTS"`
-	UpdateTS    int64  `json:"updateTS"`
+	NodeID string `json:"nodeId"`
+	Host   string `json:"host"`
+	State  string `json:"state"`
+
+	// NB: Currently we save the whole `NodeStatus` in the status of the CR.
```
Comment (csuzhangxc) [inline pkg/binlog/binlog.go:102]: 😢

**Review by csuzhangxc — APPROVED** [review]
LGTM

File: pkg/binlog/binlog.go (hunk 4 above)
Comment (DanielZhangQD) [inline pkg/binlog/binlog.go:102]:
```suggestion
	// Previously we save the whole `NodeStatus` in the status of the CR.
```
