### PR TITLE
use the real desired replicas in HA predicate

### LINKED ISSUE #1594: the pod of pd or tikv will be pending when there are three nodes in k8s and replicas which is set by tc are above 3
## Bug Report

**What version of Kubernetes are you using?**
v1.16.3

**What version of TiDB Operator are you using?**
v1.0.5

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
local-storage

**What's the status of the TiDB cluster pods?**
tidbcluster-wuhanwuli-tikv-0                       0/1     Pending     0          11d
tidbcluster-wuhanwuli-tikv-1                       1/1     Running     17         12d
tidbcluster-wuhanwuli-tikv-2                       1/1     Running     18         12d
tidbcluster-wuhanwuli-tikv-3                       0/1     Pending     0          12d

**What did you do?**
there are 3 nodes in k8s. make a node down, then use a new server to recover the node, make new pv in the new node.

**What did you expect to see?**
all the tikv's pods can become running

**What did you see instead?**
some of the tikv's pods are pending, unless add new nodes and new pv

### PR DESCRIPTION
**Pull request by cofyc**
### What problem does this PR solve? 
fix #1594 
### Check List 

Tests 

 - Unit test
 - E2E test
 - Stability test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has Go code change
 - Has CI related scripts change
 - Has Terraform scripts change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

File: pkg/scheduler/predicates/ha.go [hunk 1]
```diff
@@ -409,10 +409,10 @@ func getTCNameFromPod(pod *apiv1.Pod, component string) string {
 
 func getReplicasFrom(tc *v1alpha1.TidbCluster, component string) int32 {
 	if component == v1alpha1.PDMemberType.String() {
-		return tc.Spec.PD.Replicas
+		return tc.PDStsDesiredReplicas()
```
Comment (DanielZhangQD) [inline pkg/scheduler/predicates/ha.go:412]: Actually, this is not gonna work for PD, because even if there are four Pods, with three-node topology, each node can still only schedule one Pod.
But we can go with this if no better way.

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Review by weekface — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
