### PR TITLE
fix pd client tls and use table driven tests to cover tls case

### LINKED ISSUE #1450: TLS e2e test fails
## Bug Report

https://github.com/pingcap/tidb-operator/pull/1430#issuecomment-569205786.

I think it's better to have a separate test for TLS too.

### PR DESCRIPTION
**Pull request by cofyc**
### What problem does this PR solve? 
fixes #1450 
### What is changed and how does it work?

- fix pd client tls bug
- use table driven tests to cover tls case (more extensible)

### Check List 

Tests 

 - Unit test
 - E2E test

### CODE REVIEW

File: tests/e2e/tidbcluster/tidbcluster.go [hunk 1]
```diff
@@ -105,19 +104,41 @@ var _ = ginkgo.Describe("[tidb-operator] TiDBCluster", func() {
...
+					"tikv.resources.limits.storage": "1G",
+				},
+			},
+			{
+				Version: "v3.0.5",
+				Name:    "basic-v3-cluster-tls",
+				Values: map[string]string{
+					"enableTLSCluster": "true",
+				},
+			},
```
Comment (cofyc) [inline tests/e2e/tidbcluster/tidbcluster.go]: we can add more to cover various configurations of cluster
