### PR TITLE
optimize tidb upgrader

### LINKED ISSUE #4366: Is tidb upgrade need to check pod ready？
## Bug Report

**What did you do?**
Now tidb upgrade not check pod ready.Do we need to add this step to avoid ambiguity?Although we check tc.Status.TiDB.Member health status.

Ref:
https://github.com/pingcap/tidb-operator/blob/9eb0658f655986d8afbe22f154e005ac114dc962/pkg/manager/member/tidb_upgrader.go#L102

**What did you expect to see?**

**What did you see instead?**

### PR DESCRIPTION
**Pull request by mikechengwei**
### What problem does this PR solve?
Fix #4366.

### What is changed and how does it work?
Add tidb pod check.

### Code changes

- [ ] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [ ] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Comment by DanielZhangQD** [comment]
@mikechengwei Could you please fix the CI and check the comment here https://github.com/pingcap/tidb-operator/issues/4366#issuecomment-1011731870?

File: pkg/manager/member/ticdc_upgrader_test.go [hunk 1]
```diff
@@ -82,8 +82,9 @@ func TestTiCDCUpgrader_Upgrade(t *testing.T) {
 			name: "normal",
 			expectFn: func(g *GomegaWithT, tc *v1alpha1.TidbCluster, newSet *apps.StatefulSet) {
 				g.Expect(tc.Status.TiCDC.Phase).To(Equal(v1alpha1.UpgradePhase))
-				g.Expect(newSet.Spec.UpdateStrategy.RollingUpdate.Partition).To(Equal(pointer.Int32Ptr(0)))
+				g.Expect(newSet.Spec.UpdateStrategy.RollingUpdate.Partition).To(Equal(pointer.Int32Ptr(1)))
```
Comment (DanielZhangQD) [inline pkg/manager/member/ticdc_upgrader_test.go:85]: Why update this from `0` to `1`?
Because the Pod generated in L53 is not ready by default?
If this is the case, we'd better update that function to add condition true by default and add a case where the Pod is not ready.

Comment (DanielZhangQD) [reply pkg/manager/member/ticdc_upgrader_test.go:85]: Please also add a similar case for the other components.

**Review by DanielZhangQD — APPROVED** [review]
LGTM

File: pkg/manager/member/pd_upgrader_test.go [hunk 2]
```diff
@@ -41,6 +41,7 @@ func TestPDUpgraderUpgrade(t *testing.T) {
 		changePods        func(pods []*corev1.Pod)
 		changeOldSet      func(set *apps.StatefulSet)
 		transferLeaderErr bool
+		isSetPodNotReady  bool
```
Comment (DanielZhangQD) [inline pkg/manager/member/pd_upgrader_test.go:44]: This is not used.

Comment (mikechengwei) [reply pkg/manager/member/pd_upgrader_test.go]: done

**Review by KanShiori — APPROVED** [review]
