### PR TITLE
use CentOS 7 in OpenShift E2E and fix an incompatibility issue

### LINKED ISSUE #2890: e2e: Red Hat CRC fails to start the latest OpenShift 4 on the CentOS 8
```
01:55:15  level=info msg="Checking size of the disk image /home/vagrant/.crc/cache/crc_libvirt_4.4.8/crc.qcow2 ..."
01:55:15  level=info msg="Creating CodeReady Containers VM for OpenShift 4.4.8..."
01:55:29  level=error msg="Error creating host: Error creating the VM: Error creating machine: Error in driver during machine creation: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2020-07-08T17:55:28.802308Z qemu-kvm: error: failed to set MSR 0x48e to 0xf7b9fffe04006172\nqemu-kvm: /builddir/build/BUILD/qemu-2.12.0/target/i386/kvm.c:2119: kvm_buf_set_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.')"
```

### PR DESCRIPTION
**Pull request by cofyc**
### What problem does this PR solve? 
fixes #2890 
### Check List 

Tests 

 - Unit test
 - E2E test
 - Stability test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has Go code change
 - Has CI related scripts change
 - Has Terraform scripts change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

File: hack/e2e-openshift.sh [hunk 1]
```diff
@@ -41,6 +41,7 @@ else
 fi
 
 echo "info: install required software packages"
+sudo yum install -y NetworkManager
```
Comment (cofyc) [inline hack/e2e-openshift.sh:44]: install explicitly

File: charts/tidb-operator/templates/scheduler-deployment.yaml [hunk 2]
```diff
@@ -48,7 +48,7 @@ spec:
           value: {{ .Values.timezone | default "UTC" }}
       {{- end }}
       - name: kube-scheduler
-        image: {{ required "scheduler.kubeSchedulerImageName is required" .Values.scheduler.kubeSchedulerImageName }}:{{ .Values.scheduler.kubeSchedulerImageTag | default (split "-" .Capabilities.KubeVersion.GitVersion)._0 }}
+        image: {{ required "scheduler.kubeSchedulerImageName is required" .Values.scheduler.kubeSchedulerImageName }}:{{- template "kube-scheduler.image_tag" . }}
```
Comment (cofyc) [inline charts/tidb-operator/templates/scheduler-deployment.yaml:51]: the old way only works for `vX.Y.Z-xxx` version, however the version of OpenShift is `v1.17.1+3f6f40d`

**Comment by cofyc** [comment]
https://internal.pingcap.net/idc-jenkins/view/tidb-operator/job/tidb-operator-e2e-openshift-ci-master/113/
