### PR TITLE
fix stability test blockwriter image

### LINKED ISSUE #1393: Pod "blockwriter" is invalid: spec.containers[0].image: Required value
Can't run stability test on the `master` branch of tidb-operator:

```
I1223 03:22:23.873205       1 log.go:172] http: TLS handshake error from 10.233.112.192:42666: remote error: tls: bad certificate
I1223 03:23:21.350457       1 actions.go:3274] cluster: [ns2/cluster2] recoding event: CleanTidbCluster
I1223 03:23:21.382570       1 actions.go:3274] cluster: [ns2/cluster2] recoding event: DeployTidbCluster
I1223 03:23:26.504053       1 actions.go:2007] monitor ready replicas 0 < 1
I1223 03:23:50.827732       1 log.go:172] http: TLS handshake error from 10.233.112.192:43416: remote error: tls: bad certificate
I1223 03:24:01.498453       1 actions.go:3274] cluster: [ns1/cluster1] recoding event: DeployTidbCluster
I1223 03:24:11.552911       1 actions.go:3274] cluster: [ns1/cluster1] recoding event: CleanTidbCluster
I1223 03:24:27.075376       1 actions.go:904] checking tidb cluster [ns2/cluster2] status
I1223 03:24:27.075487       1 actions.go:3202] Event: BeginInsertData: concurrency: 4
I1223 03:24:37.127175       1 actions.go:3274] cluster: [ns1/cluster1] recoding event: BeginInsertData: concurrency: 4
panic: Pod "blockwriter" is invalid: spec.containers[0].image: Required value
goroutine 9217 [running]:
github.com/pingcap/tidb-operator/tests/slack.NotifyAndPanic(0x21221c0, 0xc00017fd60)
	github.com/pingcap/tidb-operator@/tests/slack/slack.go:156 +0x270
github.com/pingcap/tidb-operator/tests.(*operatorActions).BeginInsertDataToOrDie(0xc00027a500, 0xc000250400)
	github.com/pingcap/tidb-operator@/tests/actions.go:1050 +0x5c
created by main.run.func2
	github.com/pingcap/tidb-operator@/tests/cmd/stability/main.go:149 +0x223
```

### PR DESCRIPTION
**Pull request by shonge**
### What problem does this PR solve? 
fix #1393 
### What is changed and how does it work?
add cfg.E2EImage

### Check List 

Tests 

 - Unit test
 - E2E test
 - Stability test

Code changes

 - Has test code change

Side effects

Related changes

 - Need to cherry-pick to the release branch

### Does this PR introduce a user-facing change?:
 
 ```release-note
NONE
 ```

### CODE REVIEW

**Comment by cofyc** [comment]
cc @weekface

File: tests/config.go [hunk 1]
```diff
@@ -100,6 +100,7 @@ func NewConfig() (*Config, error) {
 	flag.StringVar(&cfg.TidbVersions, "tidb-versions", "v3.0.2,v3.0.3,v3.0.4,v3.0.5", "tidb versions")
 	flag.StringVar(&cfg.OperatorTag, "operator-tag", "master", "operator tag used to choose charts")
 	flag.StringVar(&cfg.OperatorImage, "operator-image", "pingcap/tidb-operator:latest", "operator image")
+	flag.StringVar(&cfg.E2EImage, "E2E-image", "pingcap/tidb-operator-e2e:latest", "operator-e2e image")
```
Comment (weekface) [inline tests/config.go]:
```suggestion
	flag.StringVar(&cfg.E2EImage, "e2e-image", "pingcap/tidb-operator-e2e:latest", "operator-e2e image")
```

**Comment by cofyc** [comment]
Thanks!
