### PR TITLE
br: fix operator panic when upgrade

### LINKED ISSUE #6304: br: fix operator panic when upgrade with a running backupSchedule
## Bug Report

**What did you do?**

1. start a backup schedule with log backup
2. upgrade to operator 1.6.2

**What did you expect to see?**

nothing happen and operator works fine

**What did you see instead?**

operator panic 

```
panic({0x3b96700?, 0x68c1330?})
	runtime/panic.go:785 +0x132
github.com/pingcap/tidb-operator/pkg/backup/backupschedule.(*backupScheduleManager).getLogBackupCheckpoint(0xc000918430, 0xc007410008)
	github.com/pingcap/tidb-operator/pkg/backup/backupschedule/backup_schedule_manager.go:381 +0x408
github.com/pingcap/tidb-operator/pkg/backup/backupschedule.(*backupScheduleManager).Sync(0xc000918430, 0xc007410008)
	github.com/pingcap/tidb-operator/pkg/backup/backupschedule/backup_schedule_manager.go:141 +0xb4
github.com/pingcap/tidb-operator/pkg/controller/backupschedule.(*defaultBackupScheduleControl).updateBackupSchedule(...)
	github.com/pingcap/tidb-operator/pkg/controller/backupschedule/backup_schedule_control.go:69
github.com/pingcap/tidb-operator/pkg/controller/backupschedule.(*defaultBackupScheduleControl).UpdateBackupSchedule(0xc000737700, 0xc007410008)
	github.com/pingcap/tidb-operator/pkg/controller/backupschedule/backup_schedule_control.go:54 +0x83
github.com/pingcap/tidb-operator/pkg/controller/backupschedule.(*Controller).syncBackupSchedule(...)
	github.com/pingcap/tidb-operator/pkg/controller/backupschedule/backup_schedule_controller.go:155
github.com/pingcap/tidb-operator/pkg/controller/backupschedule.(*Controller).sync(0xc000a82930, {0xc000bc67c0, 0x1e})
	github.com/pingcap/tidb-operator/pkg/controller/backupschedule/backup_schedule_controller.go:151 +0x1bb
github.com/pingcap/tidb-operator/pkg/controller/backupschedule.(*Controller).processNextWorkItem(0xc000a82930)
	github.com/pingcap/tidb-operator/pkg/controller/backupschedule/backup_schedule_controller.go:103 +0x1cd
github.com/pingcap/tidb-operator/pkg/controller/backupschedule.(*Controller).worker(...)
	github.com/pingcap/tidb-operator/pkg/controller/backupschedule/backup_schedule_controller.go:88
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	k8s.io/apimachinery@v0.28.14/pkg/util/wait/backoff.go:226 +0x33
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc007400040, {0x4938c80, 0xc007406000}, 0x1, 0xc000816d90)
	k8s.io/apimachinery@v0.28.14/pkg/util/wait/backoff.go:227 +0xaf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc007400040, 0x3b9aca00, 0x0, 0x1, 0xc000816d90)
	k8s.io/apimachinery@v0.28.14/pkg/util/wait/backoff.go:204 +0x7f
k8s.io/apimachinery/pkg/util/wait.Until(...)
	k8s.io/apimachinery@v0.28.14/pkg/util/wait/backoff.go:161
created by github.com/pingcap/tidb-operator/pkg/controller/backupschedule.(*Controller).Run in goroutine 427
	github.com/pingcap/tidb-operator/pkg/controller/backupschedule/backup_schedule_controller.go:80 +0x13c
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x273be68]
```

### PR DESCRIPTION
**Pull request by RidRisR**
### What problem does this PR solve?

    Closes #6304 

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

Note: Now the default compact.Spec.startTs is set to logBackup.startTs, for compact could automatically determine if the data has been compacted.

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [x] Manual test 
- [ ] No code 

```shell
# Apply the backup schedule before upgrade
[root@virtualmachine-6 k8s-test]# kubectl describe bks
Name:         integrated-backup-1
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  pingcap.com/v1alpha1
Kind:         BackupSchedule
Metadata:
  Creation Timestamp:  2025-07-16T08:43:33Z
  Generation:          2
  Resource Version:    1329
  UID:                 ec029cfd-33fe-49f5-946b-456d177d6a2b
Spec:
  Backup Template:
    Backoff Retry Policy:
      Max Retry Times:     2
      Min Retry Duration:  300s
      Retry Timeout:       30m
    Backup Mode:           snapshot
    Backup Type:           full
    Br:
      Cluster:            basic
      Cluster Namespace:  default
      Send Cred To Tikv:  true
    Calc Size Level:      all
    Clean Policy:         Delete
    Resources:
    s3:
      Bucket:                                   tmp
      Endpoint:                                 http://minio.pingcap.net:9000
      Prefix:                                   ris-test7
      Provider:                                 minio
      Secret Name:                              s3-secret
    Volume Backup Init Job Max Active Seconds:  600
  Log Backup Template:
    Backoff Retry Policy:
      Max Retry Times:     2
      Min Retry Duration:  300s
      Retry Timeout:       30m
    Backup Mode:           log
    Br:
      Cluster:            basic
      Cluster Namespace:  default
      Send Cred To Tikv:  true
    Calc Size Level:      all
    Clean Policy:         Retain
    Resources:
    s3:
      Bucket:                                   tmp
      Endpoint:                                 http://minio.pingcap.net:9000
      Prefix:                                   ris-test7
      Provider:                                 minio
      Secret Name:                              s3-secret
    Volume Backup Init Job Max Active Seconds:  600
  Max Reserved Time:                            30m
  Schedule:                                     0/15 * * * *
Status:
  Log Backup:  log-integrated-backup-1
Events:        <none>

# After upgrade
[root@virtualmachine-6 k8s-test]# kubectl get bk
NAME                      TYPE   MODE   STATUS    BACKUPPATH                                   BACKUPSIZE   COMMITTS             LOGTRUNCATEUNTIL   TIMETAKEN   AGE
log-integrated-backup-1          log    Running   s3://tmp/ris-test7/log-2025-07-16t08-43-33                459448105730834433                                  42s
info: waiting for pods of deployment pingcap/tidb-controller-manager are ready (retries: 300, interval: 1s)
info: pods of deployment pingcap/tidb-controller-manager (desired: 1, ready: )
info: pods of deployment pingcap/tidb-controller-manager (desired: 1, ready: )
info: pods of deployment pingcap/tidb-controller-manager (desired: 1, ready: )
info: pods of deployment pingcap/tidb-controller-manager (desired: 1, ready: )
info: all pods of deployment pingcap/tidb-controller-manager are ready (desired: 1, ready: 1)
[root@virtualmachine-6 k8s-test]#   kubectl logs $(kubectl get pods -n pingcap -l app.kubernetes.io/component=controller-manager,app.kubernetes.io/name=tidb-operator -o jsonpath='{.items[0].metadata.name}') -n pingcap --tail=1000 > log
[root@virtualmachine-6 k8s-test]# 
[root@virtualmachine-6 k8s-test]# kubectl get bks
NAME                  SCHEDULE       MAXBACKUPS   MAXRESERVEDTIME   AGE
integrated-backup-1   0/15 * * * *                30m               3m38s
[root@virtualmachine-6 k8s-test]# kubectl get pod -n pingcap
NAME                                       READY   STATUS    RESTARTS   AGE
tidb-controller-manager-765dc44756-vhxvt   1/1     Running   0          65s


# tidb-operator should work fine
I0716 08:46:34.974660       1 request.go:629] Waited for 193.675493ms due to client-side throttling, not priority and fairness, request: GET:https://10.43.0.1:443/apis/pingcap.com/v1alpha1/namespaces/default/backups/log-integrated-backup-1
E0716 08:46:34.979530       1 backup_schedule_manager.go:384] backup schedule default/integrated-backup-1, log backup log-integrated-backup-1 start ts not set, maybe upgraded from older version. It would be set to 2025-07-16 08:46:34.979521803 +0000 UTC m=+17.667171932.
I0716 08:46:34.979606       1 backup_schedule_manager.go:452] unmet backup schedule default/integrated-backup-1 start time, waiting for the next backup schedule period
I0716 08:46:34.979616       1 backup_schedule_manager.go:165] backupSchedule default/integrated-backup-1 next scheduled time is <nil>
I0716 08:46:34.979718       1 backup_schedule_control.go:60] backupSchedule default/integrated-backup-1 status updated
```

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

File: pkg/backup/backupschedule/backup_schedule_manager.go [hunk 1]
```diff
@@ -378,6 +378,28 @@ func (bm *backupScheduleManager) getLogBackupCheckpoint(bs *v1alpha1.BackupSched
 	if err != nil {
 		return nil, err
 	}
+
+	if bs.Status.LogBackupStartTs == nil {
```
Comment (WangLe1321) [inline pkg/backup/backupschedule/backup_schedule_manager.go:391]: You should check if the checkpoint is valid, or the log backup is running. If the log backup is starting, the commit ts in status may be empty.

Comment (RidRisR) [reply pkg/backup/backupschedule/backup_schedule_manager.go:391]: This branch is in the `getLogBackupCheckpoint`, which guarantees the existence of checkpoint.

**Review by WangLe1321 — APPROVED** [review]
