### PR TITLE
Convert capacity into MiB for tikv-server when necessary

### LINKED ISSUE #941: Convert capacity into megabytes for tikv-server when necessary
## Bug Report

If the given capacity is less than 1 GB or not a multiple of GB. We can convert it to megabytes instead.

### PR DESCRIPTION
**Pull request by cofyc**
### What problem does this PR solve? 

fixes #941 

### Check List 

Tests 

 - Unit test

### Does this PR introduce a user-facing change?:
 
 ```release-note
Convert tikv capacity into MiB when it's not a multiple of GiB.
 ```

### CODE REVIEW

File: pkg/controller/controller_utils_test.go [hunk 1]
```diff
@@ -125,10 +125,29 @@ func TestTiKVCapacity(t *testing.T) {
 		{
 			name: "100GiB",
 			limit: &v1alpha1.ResourceRequirement{
-				Storage: "100Gi",
+				Storage: "100GiB",
```
Comment (cofyc) [inline pkg/controller/controller_utils_test.go]: `Storage: "100Gi"` has already been tested in previous test case. I guess this should be `100GiB`.

**Comment by cofyc** [comment]
Perhaps, rounding down is better than rounding up here, because it’s capacity limit.
