### PR TITLE
set failurePolicy to Fail in e2e

### LINKED ISSUE #2430: e2e: “Upgrading TiDB Cluster“ is flaky in kind job
## Bug Report

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/operator_ghpr_e2e_test_kind/detail/operator_ghpr_e2e_test_kind/5401/tests

```
tacktrace
/home/jenkins/agent/workspace/operator_ghpr_e2e_test_kind/go/src/github.com/pingcap/tidb-operator/tests/e2e/tidbcluster/tidbcluster.go:228
Test Panicked
/home/jenkins/agent/workspace/operator_ghpr_e2e_test_kind/go/src/github.com/pingcap/tidb-operator/tests/slack/slack.go:169
Panic: pause partition is not correct in upgrade phase [tidb-cluster-8173/cluster-tidb] partition 0 annotation 1
Full stack:
github.com/pingcap/tidb-operator/tests/slack.NotifyAndPanic(0x3dbe060, 0xc0007fbfd0)
/home/jenkins/agent/workspace/operator_ghpr_e2e_test_kind/go/src/github.com/pingcap/tidb-operator/tests/slack/slack.go:169 +0x270
github.com/pingcap/tidb-operator/tests.(*operatorActions).CheckUpgradeOrDie(0xc0013ae9c0, 0x3e2b7a0, 0xc000e9f780, 0xc00079ba00)
/home/jenkins/agent/workspace/operator_ghpr_e2e_test_kind/go/src/github.com/pingcap/tidb-operator/tests/actions.go:1355 +0x70
github.com/pingcap/tidb-operator/tests/e2e/tidbcluster.glob..func3.5()
/home/jenkins/agent/workspace/operator_ghpr_e2e_test_kind/go/src/github.com/pingcap/tidb-operator/tests/e2e/tidbcluster/tidbcluster.go:252 +0x86c
github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc000450ea0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/go/pkg/mod/github.com/onsi/ginkgo@v1.10.3/internal/leafnodes/runner.go:113 +0xb8
github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc000450ea0, 0xc0001760c8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/go/pkg/mod/github.com/onsi/ginkgo@v1.10.3/internal/leafnodes/runner.go:64 +0xcf
github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run(0xc000611520, 0x3dbf540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/go/pkg/mod/github.com/onsi/ginkgo@v1.10.3/internal/leafnodes/it_node.go:26 +0x64
github.com/onsi/ginkgo/internal/spec.(*Spec).runSample(0xc0001f8d20, 0x0, 0x3dbf540, 0xc000184680)
/go/pkg/mod/github.com/onsi/ginkgo@v1.10.3/internal/spec/spec.go:215 +0x5b5
github.com/onsi/ginkgo/internal/spec.(*Spec).Run(0xc0001f8d20, 0x3dbf540, 0xc000184680)
/go/pkg/mod/github.com/onsi/ginkgo@v1.10.3/internal/spec/spec.go:138 +0x101
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec(0xc000a9c000, 0xc0001f8d20, 0x0)
/go/pkg/mod/github.com/onsi/ginkgo@v1.10.3/internal/specrunner/spec_runner.go:200 +0x10f
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc000a9c000, 0x1)
/go/pkg/mod/github.com/onsi/ginkgo@v1.10.3/internal/specrunner/spec_runner.go:170 +0x120
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc000a9c000, 0xc00043a618)
/go/pkg/mod/github.com/onsi/ginkgo@v1.10.3/internal/specrunner/spec_runner.go:66 +0x117
github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc00019a140, 0x7f7dc4e12a00, 0xc000a52900, 0x37f6f4f, 0x17, 0xc000585540, 0x2, 0x2, 0x3e51860, 0xc000184680, ...)
/go/pkg/mod/github.com/onsi/ginkgo@v1.10.3/internal/suite/suite.go:62 +0x42b
github.com/onsi/ginkgo.RunSpecsWithCustomReporters(0x3dc1a20, 0xc000a52900, 0x37f6f4f, 0x17, 0xc000585500, 0x2, 0x2, 0x2)
/go/pkg/mod/github.com/onsi/ginkgo@v1.10.3/ginkgo_dsl.go:226 +0x217
github.com/onsi/ginkgo.RunSpecsWithDefaultAndCustomReporters(0x3dc1a20, 0xc000a52900, 0x37f6f4f, 0x17, 0xc000428a30, 0x1, 0x1, 0x1)
/go/pkg/mod/github.com/onsi/ginkgo@v1.10.3/ginkgo_dsl.go:214 +0xad
github.com/pingcap/tidb-operator/tests/e2e.RunE2ETests(0xc000a52900)
/home/jenkins/agent/workspace/operator_ghpr_e2e_test_kind/go/src/github.com/pingcap/tidb-operator/tests/e2e/e2e.go:401 +0x242
github.com/pingcap/tidb-operator/tests/e2e.TestE2E(0xc000a52900)
/home/jenkins/agent/workspace/operator_ghpr_e2e_test_kind/go/src/github.com/pingcap/tidb-operator/tests/e2e/e2e_test.go:142 +0x2b
testing.tRunner(0xc000a52900, 0x3907948)
/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
/usr/local/go/src/testing/testing.go:960 +0x350
```

this is because the default `failurePolicy` of admission webhook is `Ignore`, and we will delete tidb-operator pods in e2e.

### PR DESCRIPTION
**Pull request by cofyc**
### What problem does this PR solve? 
fixes #2430
### Check List 

Tests 

 - Unit test
 - E2E test
 - Stability test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has Go code change
 - Has CI related scripts change
 - Has Terraform scripts change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

File: tests/e2e/config/config.go [hunk 1]
```diff
@@ -109,6 +109,10 @@ func NewDefaultOperatorConfig(cfg *tests.Config) *tests.OperatorConfig {
 		PodWebhookEnabled:         false,
 		Cabundle:                  "",
 		BackupImage:               cfg.BackupImage,
+		StringValues: map[string]string{
+			"admissionWebhook.failurePolicy.validation": "Fail",
+			"admissionWebhook.failurePolicy.mutation":   "Fail",
+		},
```
Comment (cofyc) [inline tests/e2e/config/config.go:115]: we will try to kill tidb-operator pods in e2e. we should fail API requests otherwise some tests will fail if the admission webhook is absent.

File: charts/tidb-operator/templates/admission/admission-webhook-deployment.yaml [hunk 2]
```diff
@@ -36,6 +36,7 @@ spec:
             - --tls-cert-file=/var/serving-cert/tls.crt
             - --tls-private-key-file=/var/serving-cert/tls.key
             {{- end }}
+            - --v={{ .Values.admissionWebhook.logLevel }}
```
Comment (cofyc) [inline charts/tidb-operator/templates/admission/admission-webhook-deployment.yaml:39]: able to specify log level verbosity for admission-webhook

**Comment by cofyc** [comment]
fixed some more e2e issues and upgraded advanced statefulset to fix an issue with k8s 1.18
@DanielZhangQD @Yisaer PTAL again
