### PR TITLE
scaling for tiflash

### LINKED ISSUE #2218: Cannot start tiflash if TimeZone is not set
## Bug Report

**What version of Kubernetes are you using?**

v1.15.2

**What version of TiDB Operator are you using?**

The latest release

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

Deploy a TiDB cluster with TiFlash. However, I didn't set the TimeZone field in TiDBClusterSpec, because I thought the default value is `UTC`. However, TiFlash cannot start if TimeZone is not set explicitly. The error is

```
➜  tipocket git:(add-tiflash-crd) ✗ klo yeya24-tiflash-0 -c tiflash
Logging information to /data0/logs/server.log
Logging errors to /data0/logs/error.log
Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Exception: Could not determine time zone from TZ variable value: '': boost::filesystem::file_size: Operation not permitted: "/usr/share/zoneinfo", e.what() = Exception
```

If I set the TimeZone in the spec manually, then TiFlash can start correctly.

**What did you expect to see?**

If I didn't set the TimeZone field, TiFlash can still start normally, since it will use the default time zone `UTC`.

**What did you see instead?**

The time zone env var in TiFlash is "". 
The problem is in the code below, I think we should use `tc.TimeZone()` instead of using `tc.Spec.Timezone`

``` Go
		{
			Name:  "TZ",
			Value: tc.Spec.Timezone,
		},
```

### PR DESCRIPTION
**Pull request by DanielZhangQD**
### What problem does this PR solve? 
Scaling for TiFlash 
### What is changed and how does it work?
Add new function to support scaling TiFlash
### Check List 

Tests 

 - Unit test
 - Manual test (add detailed scripts or steps below)
    - Scale-out TiFlash successfully, Scale in TiFlash successfully, the store is deleted and the PVCs are marked as defer deleting, Scale-out TiFlash again and the old PVCs are removed and the scaling out succeeds.
    - Scale-out PD successfully, Scale in PD successfully, the member is deleted and the PVC is marked as defer deleting, Scale-out PD again and the old PVC is removed and the scaling out succeeds.

Code changes

 - Has Go code change

### Does this PR introduce a user-facing change?:

```release-note
Support scaling for TiFlash
```

### CODE REVIEW

File: pkg/controller/pod_control.go [hunk 1]
```diff
@@ -305,7 +305,6 @@ func (fpc *FakePodControl) UpdateMetaInfo(_ *v1alpha1.TidbCluster, pod *corev1.P
 	}
 
 	setIfNotEmpty(pod.Labels, label.NameLabelKey, TestName)
-	setIfNotEmpty(pod.Labels, label.ComponentLabelKey, TestComponentName)
```
Comment (DanielZhangQD) [inline pkg/controller/pod_control.go:308]: No need to set it here, the caller function already set it and this will overwrite the setting in the cases.

File: pkg/controller/pvc_control.go [hunk 2]
```diff
@@ -127,6 +127,7 @@ func (rpc *realPVCControl) UpdateMetaInfo(tc *v1alpha1.TidbCluster, pvc *corev1.
 	if pvc.Labels[label.ClusterIDLabelKey] == clusterID &&
 		pvc.Labels[label.MemberIDLabelKey] == memberID &&
 		pvc.Labels[label.StoreIDLabelKey] == storeID &&
+		pvc.Labels[label.AnnPodNameKey] == podName &&
```
Comment (DanielZhangQD) [inline pkg/controller/pvc_control.go:130]: Add pod name label so we can list all the PVCs of one Pod.

File: pkg/manager/member/pd_member_manager.go [hunk 3]
```diff
@@ -713,7 +713,15 @@ func getPDConfigMap(tc *v1alpha1.TidbCluster) (*corev1.ConfigMap, error) {
 		config.Dashboard.TiDBCertPath = path.Join(tidbClientCertPath, corev1.TLSCertKey)
 		config.Dashboard.TiDBKeyPath = path.Join(tidbClientCertPath, corev1.TLSPrivateKeyKey)
 	}
-
+	if tc.Spec.TiFlash != nil {
```
Comment (DanielZhangQD) [inline pkg/manager/member/pd_member_manager.go:716]: If TiFlash is enabled and EnablePlacementRules is not set explicitly, enable it.

File: pkg/manager/member/orphan_pods_cleaner.go [hunk 4]
```diff
@@ -92,39 +92,46 @@ func (opc *orphanPodsCleaner) Clean(tc *v1alpha1.TidbCluster) (map[string]string
 			continue
 		}
 
-		// TODO support multiple pvcs case?
-		var pvcName string
+		var pvcName []string
```
Comment (weekface) [inline pkg/manager/member/orphan_pods_cleaner.go:95]:
```suggestion
		var pvcNames []string
```

Comment (DanielZhangQD) [reply pkg/manager/member/orphan_pods_cleaner.go]: updated.

**Comment by DanielZhangQD** [comment]
@weekface comments addressed, PTAL.

**Comment by yeya24** [comment]
Thanks for the fix. Is there a rc release for this?

File: pkg/manager/member/pd_member_manager.go (hunk 3 above)
Comment (Yisaer) [reply pkg/manager/member/pd_member_manager.go:716]: Can we add a document to explain why EnablePlacementRules is necessary for tiflash

File: pkg/manager/member/tiflash_scaler.go [hunk 5]
```diff
@@ -47,13 +53,114 @@ func (tfs *tiflashScaler) Scale(tc *v1alpha1.TidbCluster, oldSet *apps.StatefulS
...
-	return nil
+	klog.Infof("scaling in tiflash statefulset %s/%s, ordinal: %d (replicas: %d, delete slots: %v)", oldSet.Namespace, oldSet.Name, ordinal, replicas, deleteSlots.List())
+	// We need delete store from cluster before decreasing the statefulset replicas
+	podName := ordinalPodName(v1alpha1.TiFlashMemberType, tcName, ordinal)
+	pod, err := tfs.podLister.Pods(ns).Get(podName)
+	if err != nil {
+		return err
+	}
+
+	if controller.PodWebhookEnabled {
```
Comment (Yisaer) [inline pkg/manager/member/tiflash_scaler.go:94]: I think we can manage tiflash scaling in the webhook  instead of in the controller as webhook would be the default choice to manage the lifecyle of each component?

File: pkg/manager/member/scaler.go [hunk 6]
```diff
@@ -54,38 +54,94 @@ type generalScaler struct {
 }
 
 func (gs *generalScaler) deleteDeferDeletingPVC(tc *v1alpha1.TidbCluster,
-	setName string, memberType v1alpha1.MemberType, ordinal int32) (map[int32]string, error) {
+	setName string, memberType v1alpha1.MemberType, ordinal int32) (map[string]string, error) {
 	ns := tc.GetNamespace()
 	// for unit test
-	skipReason := map[int32]string{}
+	skipReason := map[string]string{}
```
Comment (Yisaer) [inline pkg/manager/member/scaler.go:60]: Why change the skipReason type here, is it for the legibility？

Comment (DanielZhangQD) [reply pkg/manager/member/scaler.go:60]: Now there will be multiple PVCs for one Pod, the `string` will be podName if no PVC found for the Pod and will be the pvcName if any PVC found, and then we can verify the result in the UT cases.

File: pkg/manager/member/tiflash_scaler.go (hunk 5 above)
Comment (DanielZhangQD) [reply pkg/manager/member/tiflash_scaler.go:94]: When will Webhook be the default choice? I think it's not decided yet, btw, before v1.15, all of the requests for Pod will be sent to the Webhook if enabled, if something wrong with the Webhook, it will block the whole cluster, so I would like to support it in controller first.

File: pkg/manager/member/pd_member_manager.go (hunk 3 above)
Comment (DanielZhangQD) [reply pkg/manager/member/pd_member_manager.go:718]: Updated

**Comment by DanielZhangQD** [comment]
@Yisaer comments addressed, PTAL.

**Comment by DanielZhangQD** [comment]
> Thanks for the fix. Is there a rc release for this?

The fixes for #2218 and #2219 are moved to https://github.com/pingcap/tidb-operator/pull/2242 and it will be cherry-picked to release-1.1, whether to release another rc is not determined yet.
