### PR TITLE
stop backup job before cleanup `Backup`

### LINKED ISSUE #4099: legacy backup data after cleanup
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

Deploy a `Backup` whose `cleanPolicy`  is "Delete", and delete Backup CR while backup pod is running. 

**What did you expect to see?**
All files are cleaned up.

**What did you see instead?**
After cleaning up, there are still some files that haven't been cleaned up.

### PR DESCRIPTION
**Pull request by KanShiori**
### What problem does this PR solve?

Fix #4099
### What is changed and how does it work?

wait for backup job to finish before clean job is created. If the backup job is running, will delete it.

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [x] Unit test 
- [ ] E2E test 
- [x] Manual test 
* Delete a `Backup` when the backup job is running
   1. Deploy a `Backup`.
   2. Delete the `Backup` when the backup job is running.
   3. Check if the backup job is deleted before the cleanup job is created.
   4. Check if the cleanup job is created.
   5. Check all data in storage is deleted.
* Delete a  `Backup` when the backup job is completed
   1. Deploy a `Backup` and wait for it to be completed.
   2. Delete the `Backup`.
   3. Check if the backup job isn't deleted and the cleanup job is created.
   4. Check all data in storage is deleted.
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note
Fix the issue that backup data maybe remain after cleaning running backup
```

### CODE REVIEW

**Review by csuzhangxc — APPROVED** [review]

File: pkg/backup/backup/backup_cleaner.go [hunk 1]
```diff
@@ -55,11 +57,23 @@ func (bc *backupCleaner) Clean(backup *v1alpha1.Backup) error {
...
 	name := backup.GetName()
+	backupJobName := backup.GetBackupJobName()
+
+	klog.Infof("start to ensure that backup %s/%s job %s have finished", ns, name, backupJobName)
+
+	finished, err := bc.ensureBackupJobFinished(backup)
+	if err != nil {
+		return fmt.Errorf("ensure %s/%s job %s finished failed: %s", ns, name, backupJobName, err)
+	}
+	if !finished {
```
Comment (july2993) [inline pkg/backup/backup/backup_cleaner.go:68]: caller of `Clean` no need to know if it cleans success or not finished?

File: pkg/controller/backup/backup_controller.go [hunk 2]
```diff
@@ -197,6 +203,42 @@ func (c *Controller) updateBackup(cur interface{}) {
...
+	owner := metav1.GetControllerOf(job)
+	if owner == nil {
+		return nil
+	}
+
+	if owner.Kind != controller.BackupControllerKind.Kind {
+		return nil
+	}
+
+	backup, err := c.deps.BackupLister.Backups(namespace).Get(owner.Name)
```
Comment (july2993) [inline pkg/controller/backup/backup_controller.go:232]: do we need to handle error?

File: pkg/backup/backup/backup_cleaner.go (hunk 1 above)
Comment (KanShiori) [reply pkg/backup/backup/backup_cleaner.go:68]: `Clean` just deploy a job. The result of clean is represented by the `Backup`'s status

File: pkg/controller/backup/backup_controller.go [hunk 3]
```diff
@@ -53,13 +55,17 @@ func NewController(deps *controller.Dependencies) *Controller {
 	}
 
 	backupInformer := deps.InformerFactory.Pingcap().V1alpha1().Backups()
+	jobInformer := deps.KubeInformerFactory.Batch().V1().Jobs()
 	backupInformer.Informer().AddEventHandler(cache.ResourceEventHandlerFuncs{
 		AddFunc: c.updateBackup,
```
Comment (july2993) [inline pkg/controller/backup/backup_controller.go:60]: why we are enqueueing it but handle it directly

Comment (KanShiori) [reply pkg/controller/backup/backup_controller.go:60]: To my knowledge, in order to don't block `Informer`'s execution.

File: pkg/controller/backup/backup_controller.go (hunk 2 above)
Comment (KanShiori) [reply pkg/controller/backup/backup_controller.go:232]: I copy code from https://github.com/pingcap/tidb-operator/blob/0dc4c4f3d878529a7c49f64e99cd992d55236bc9/pkg/controller/tidbcluster/tidb_cluster_controller.go#L250

Or, we add some logs to print errors?

**Review by july2993 — APPROVED** [review]

File: pkg/backup/backup/backup_cleaner.go [hunk 4]
```diff
@@ -55,11 +57,23 @@ func (bc *backupCleaner) Clean(backup *v1alpha1.Backup) error {
...
+		klog.Infof("wait for backup %s/%s job %s to finish", ns, name, backupJobName)
```
Comment (DanielZhangQD) [inline pkg/backup/backup/backup_cleaner.go:69]: Should we return error to trigger resync here?

Comment (KanShiori) [reply pkg/backup/backup/backup_cleaner.go:69]: Use informer to watch job in BackupController, so when the backup job finish, it will trigger resync.

Comment (DanielZhangQD) [reply pkg/backup/backup/backup_cleaner.go:69]: But you only handle the delete event now, when the job is finished, it will not trigger resync, the code implemented now can trigger resync when you delete the job in the `Clean` function, anyway, we also have resync period with 30s by default.

Comment (KanShiori) [reply pkg/backup/backup/backup_cleaner.go:69]: Function `ensureBackupJobFinished` will delete the job if it is running. It means that if the return `finished` is false, the job will be deleted.

Comment (DanielZhangQD) [reply pkg/backup/backup/backup_cleaner.go:69]: ok
