### PR TITLE
tc: delete tiflash sts before scale from 0

### LINKED ISSUE #4843: TiFlash re-scale from 0 stuck if with a less storage than previous
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

v1.4.0

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

in AWS EKS with EBS PV

**What's the status of the TiDB cluster pods?**

**What did you do?**

1. create a TiFlash with 1 replica and 110G storage and m6g.xlarge instance in AWS EKS
2. scale TiFlash to 0
3. scale TiFlash to 1 with 100G storage

**What did you expect to see?**

tc synced and the following tiflash status

```
      volumes:
        data0:
          boundCount: 1
          currentCapacity: 100Gi
          currentCount: 1
          currentStorageClass: tiflash-gp3-6000-625
          modifiedCapacity: 100Gi
          modifiedCount: 1
          modifiedStorageClass: tiflash-gp3-6000-625
          name: data0
          resizedCapacity: 100Gi
          resizedCount: 1
```

**What did you see instead?**

```
      volumes:
        data0:
          boundCount: 1
          currentCapacity: 110Gi
          currentCount: 1
          currentStorageClass: tiflash-gp3-6000-625
          modifiedCapacity: 100Gi
          modifiedCount: 0
          modifiedStorageClass: tiflash-gp3-6000-625
          name: data0
          resizedCapacity: 100Gi
          resizedCount: 0
```

### PR DESCRIPTION
**Pull request by csuzhangxc**
### What problem does this PR solve?

fix #4843 

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [x] Manual test 
    1. create a TiFlash with 1 replica and 110G storage and `m6g.xlarge` instance in AWS EKS
    2. scale TiFlash to 0
    3. scale TiFlash to 1 with 100G storage
    4. TiFlash becomes ready and tc synced, TiFlash volume status with `modifiedCapacity: 100Gi` and `modifiedCount: 1`
    5. scale TiFlash to 0
    6. scale TiFlash to 1 with `t4g.medium` instance
    7. TiFlash becomes ready and tc synced
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

File: pkg/manager/member/tiflash_member_manager.go [hunk 1]
```diff
@@ -212,6 +212,15 @@ func (m *tiflashMemberManager) syncStatefulSet(tc *v1alpha1.TidbCluster) error {
 	}
 	setNotExist := errors.IsNotFound(err)
 
+	// if TiFlash is scale from 0 and with previous StatefulSet, we delete the previous StatefulSet first
+	// to avoid some fileds (e.g storage request) reused and cause unexpected behavior (e.g scale down).
+	if oldSetTmp != nil && *oldSetTmp.Spec.Replicas == 0 && tc.Spec.TiFlash.Replicas > 0 {
```
Comment (KanShiori) [inline pkg/manager/member/tiflash_member_manager.go:217]: Do we need to check the actual replica in sts status? Maybe sts is scaling in even if `spec.replicas` is 0.

Comment (csuzhangxc) [reply pkg/manager/member/tiflash_member_manager.go:217]: Deleting a scaling sts is still OK?

Comment (KanShiori) [reply pkg/manager/member/tiflash_member_manager.go:217]: seem ok

Comment (csuzhangxc) [reply pkg/manager/member/tiflash_member_manager.go:217]: https://github.com/pingcap/tidb-operator/pull/4842/commits/10594e24be3fc34671f9d8ea35bed265124c8c3d

Comment (csuzhangxc) [reply pkg/manager/member/tiflash_member_manager.go]: https://github.com/pingcap/tidb-operator/pull/4842/commits/0424db15ad4b2de0fb8c882525b7054dfcbe2387

**Review by KanShiori — APPROVED** [review]

**Review by liubog2008 — APPROVED** [review]
