### PR TITLE
separate dm and tidb monitor logic

### LINKED ISSUE #4165: Does dm monitor must have to rely on a tidb cluster?
## Bug Report

**What did you do?**
When i use tidbmonitor monitor a dm cluster,it need I have to start a tidb cluster.
Ref:
```
apiVersion: pingcap.com/v1alpha1
kind: TidbMonitor
metadata:
  name: basic
spec:
  clusters:
  - name: basic
  dm:
    clusters:
    - name: basic
    initializer:
      baseImage: pingcap/dm-monitor-initializer
      version: v2.0.6
  imagePullPolicy: IfNotPresent
```

**What did you expect to see?**
Don't rely on tidb cluster.

### PR DESCRIPTION
**Pull request by mikechengwei**
### What problem does this PR solve?
Fix #4165 

### What is changed and how does it work?
Separate dm and tidb monitor logic.
### Code changes

- [ ] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [ ] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note
Separate dm and tidb monitor code logic.
```

### CODE REVIEW

**Review by csuzhangxc — APPROVED** [review]

File: pkg/monitor/monitor/util.go [hunk 1]
```diff
@@ -1149,14 +1165,18 @@ func defaultTidbMonitor(monitor *v1alpha1.TidbMonitor) {
 	if monitor.Spec.PVReclaimPolicy == nil {
 		monitor.Spec.PVReclaimPolicy = &retainPVP
 	}
+	// If tidb clusters is null,we set a zero slice.
```
Comment (july2993) [inline pkg/monitor/monitor/util.go:1168]: why?

Comment (mikechengwei) [reply pkg/monitor/monitor/util.go:1168]: Because if `spec.clusters` field is null ,update tidb status will throw nil exception. So we need to set an empty array.

File: pkg/monitor/monitor/monitor_manager.go [hunk 2]
```diff
@@ -68,7 +68,7 @@ func (m *MonitorManager) SyncMonitor(monitor *v1alpha1.TidbMonitor) error {
 	if monitor.DeletionTimestamp != nil {
 		return nil
 	}
-	if monitor.Spec.Clusters == nil || len(monitor.Spec.Clusters) < 1 {
+	if (monitor.Spec.Clusters == nil || len(monitor.Spec.Clusters) < 1) && (monitor.Spec.DM == nil || len(monitor.Spec.DM.Clusters) < 1) {
```
Comment (july2993) [inline pkg/monitor/monitor/monitor_manager.go:71]:
```suggestion
	if len(monitor.Spec.Clusters) < 1 && (monitor.Spec.DM == nil || len(monitor.Spec.DM.Clusters) < 1) {
```

File: pkg/monitor/monitor/util.go (hunk 1 above)
Comment (july2993) [reply pkg/monitor/monitor/util.go:1168]: sorry, I can not catch the point, can you clarify it?

Comment (mikechengwei) [reply pkg/monitor/monitor/util.go:1168]: If we don't set empty array, operator update will throw below exception.
image

Comment (july2993) [reply pkg/monitor/monitor/util.go:1168]: add `omitempty` tag in `TidbMonitorSpec` for `Clusters` and drop this code?

**Review by july2993 — COMMENTED** [review]
rest LGTM

File: pkg/monitor/monitor/util.go (hunk 1 above)
Comment (mikechengwei) [reply pkg/monitor/monitor/util.go]: ok

**Comment by mikechengwei** [comment]
@csuzhangxc plz lgtm again.

File: pkg/monitor/monitor/util.go [hunk 3]
```diff
@@ -356,6 +340,26 @@ func getMonitorInitContainer(monitor *v1alpha1.TidbMonitor, tc *v1alpha1.TidbClu
 		},
 		Resources: controller.ContainerResource(monitor.Spec.Initializer.ResourceRequirements),
 	}
+	if tc != nil {
```
Comment (DanielZhangQD) [inline pkg/monitor/monitor/util.go:343]: If tc == nil, is it necessary to create the init container here? cc @csuzhangxc

File: pkg/monitor/monitor/util.go [hunk 4]
```diff
@@ -660,6 +666,14 @@ func getMonitorGrafanaContainer(secret *core.Secret, monitor *v1alpha1.TidbMonit
 			},
 		},
 	}
+	if tc != nil {
```
Comment (DanielZhangQD) [inline pkg/monitor/monitor/util.go:669]: What if this is for DM cluster only?

File: pkg/monitor/monitor/util.go [hunk 5]
```diff
@@ -804,12 +818,14 @@ func getMonitorReloaderContainer(monitor *v1alpha1.TidbMonitor, tc *v1alpha1.Tid
 			},
 		},
 		Resources: controller.ContainerResource(monitor.Spec.Reloader.ResourceRequirements),
-		Env: []core.EnvVar{
+	}
+	if tc != nil {
```
Comment (DanielZhangQD) [inline pkg/monitor/monitor/util.go:822]: What if for DM only?

File: pkg/monitor/monitor/util.go [hunk 6]
```diff
@@ -479,10 +483,7 @@ func getMonitorPrometheusContainer(monitor *v1alpha1.TidbMonitor, tc *v1alpha1.T
 			},
 		},
 		Env: []core.EnvVar{
-			{
```
Comment (DanielZhangQD) [inline pkg/monitor/monitor/util.go:482]: DM also has Timezone config.

File: pkg/controller/tidbmonitor/tidb_monitor_control.go [hunk 7]
```diff
@@ -66,6 +66,7 @@ func (c *defaultTidbMonitorControl) reconcileTidbMonitor(tm *v1alpha1.TidbMonito
 	if apiequality.Semantic.DeepEqual(&tm.Status, oldStatus) {
 		return errorutils.NewAggregate(errs)
 	}
+
```
Comment (DanielZhangQD) [inline pkg/controller/tidbmonitor/tidb_monitor_control.go:69]: Just revert this.

File: pkg/monitor/monitor/util.go [hunk 8]
```diff
@@ -528,6 +529,15 @@ func getMonitorPrometheusContainer(monitor *v1alpha1.TidbMonitor, tc *v1alpha1.T
 		},
 	}
 
+	if tc != nil {
```
[the remark this answers is not in the document]
Comment (mikechengwei) [reply pkg/monitor/monitor/util.go:532]: I have optimized ,dm will use tm default timezone,this is to help decoupling firsttc and tm.

File: pkg/monitor/monitor/util.go [hunk 9]
```diff
@@ -139,7 +139,7 @@ func getGrafanaEnvs() []core.EnvVar {
 	}
 }
 
-func getAlertManagerRulesVersion(tc *v1alpha1.TidbCluster, monitor *v1alpha1.TidbMonitor) string {
```
[the remark this answers is not in the document]
Comment (mikechengwei) [reply pkg/monitor/monitor/util.go:142]: I have add unit test for the case of cluster field not specified , i think this piece of code not need to add unit test cover it . because i just optimize input parameter.

**Comment by mikechengwei** [comment]
Manual test screenshot:
Screen Shot 2021-11-15 at 11 05 24 AM
Screen Shot 2021-11-15 at 11 07 03 AM

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Review by csuzhangxc — APPROVED** [review]
