### PR TITLE
ebs br: pass region name for aws EBS volume operation

### LINKED ISSUE #5185: there is a error "MissingRegion: could not find region configuration" in volumerestore
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**
bornchanger/tidb-operator:2023071801

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**
1. do volumebackup and there is a 3 min network loss during backup pod and pd leader
2. do volumerestore

**What did you expect to see?**
1. volumerestore success

**What did you see instead?**
1. volumerestore failed
2.
5547f986-2688-4317-b348-8e78a998b6b3

### PR DESCRIPTION
**Pull request by BornChanger**
### What problem does this PR solve?

Close #5185 

### What is changed and how does it work?

Pass the region name for EBS volume delete and addtag operation.

### Code changes

- [X] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [X] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

File: pkg/backup/restore/restore_manager.go [hunk 1]
```diff
@@ -172,7 +172,9 @@ func (rm *restoreManager) syncRestoreJob(restore *v1alpha1.Restore) error {
 					return err
 				}
 
-				err = s.AddVolumeTags(pvs)
+				if restore.Spec.S3 != nil {
+					err = s.AddVolumeTags(pvs, restore.Spec.S3.Region)
```
Comment (WangLe1321) [inline pkg/backup/restore/restore_manager.go:176]: S3 supports cross region access. So maybe s3 region is not equal to volume region. I think maybe we can get region from the restoremeta file.

Comment (BornChanger) [reply pkg/backup/restore/restore_manager.go]: Use another set of API to get EC2's region.

**Review by WangLe1321 — APPROVED** [review]
