### PR TITLE
fix random password conatin illegal character

### LINKED ISSUE #4489: E2E case for random tidb password is unstable
## Question

> /home/jenkins/agent/workspace/tidb-operator-pull-e2e-kind/go/src/github.com/pingcap/tidb-operator/tests/e2e/tidbcluster/tidbcluster.go:3297
Expected tidbcluster connect success
Unexpected error:
    <*errors.errorString | 0xc0021eb490>: {
        s: "cannot connect to tidb cluster, err: Error 1045: Access denied for user 'root'@'127.0.0.1' (using password: YES)",
    }
    cannot connect to tidb cluster, err: Error 1045: Access denied for user 'root'@'127.0.0.1' (using password: YES)
occurred
/home/jenkins/agent/workspace/tidb-operator-pull-e2e-kind/go/src/github.com/pingcap/tidb-operator/tests/e2e/tidbcluster/tidbcluster.go:3311

Seems that the password isn't correct.

Some failed CI: 
https://ci.pingcap.net/job/tidb-operator-pull-e2e-kind/2677/
https://ci.pingcap.net/job/tidb-operator-pull-e2e-kind/2671/
https://ci.pingcap.net/job/tidb-operator-pull-e2e-kind/2660/

### PR DESCRIPTION
**Pull request by mikechengwei**
### What problem does this PR solve?
Closed #4489.

### What is changed and how does it work?
validate password not contain '\' character.

### Code changes

- [ ] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [ ] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

File: pkg/manager/member/tidb_member_manager.go [hunk 1]
```diff
@@ -352,7 +352,14 @@ func (m *tidbMemberManager) buildRandomPasswordSecret(tc *v1alpha1.TidbCluster)
...
 	}
-	password := util.FixedLengthRandomPasswordBytes()
+	var password []byte
+	for {
+		password = util.FixedLengthRandomPasswordBytes()
+		// check password not contain "\" character
+		if !strings.Contains(string(password), "\\") {
+			break
+		}
+	}
```
Comment (KanShiori) [inline pkg/manager/member/tidb_member_manager.go:362]: Do we need to add a ut to cover this case?

File: pkg/manager/member/tidb_member_manager_test.go [hunk 2]
```diff
@@ -2438,3 +2438,16 @@ func mustTiDBConfig(x interface{}) *v1alpha1.TiDBConfigWraper {
...
+
+func TestBuildRandomPasswordSecret(t *testing.T) {
+	g := NewGomegaWithT(t)
+	tc := &v1alpha1.TidbCluster{
+		ObjectMeta: metav1.ObjectMeta{
+			Name: "basic",
+		},
+	}
+	tmm, _, _, _ := newFakeTiDBMemberManager()
+	_, password := tmm.BuildRandomPasswordSecret(tc)
```
Comment (KanShiori) [inline pkg/manager/member/tidb_member_manager_test.go:2450]: Emm, I think this case is unstable because the generated password is random. 
FYI, we can use the lib "github.com/agiledragon/gomonkey/v2" to mock the return for `util.FixedLengthRandomPasswordBytes`.

For example:
```go
patch:= gomonkey.ApplyFunc(util.FixedLengthRandomPasswordBytes, func() []byte {
      return "123123\zxd", nil   // return the invalid string firstly
})
defer patch.Reset()
```

Comment (mikechengwei) [reply pkg/manager/member/tidb_member_manager_test.go:2458]: If i mock "123123\zxd" password which contain `\` character, the code will block because the loop can't break.  So i use a common password to test.

**Comment by mikechengwei** [comment]
@KanShiori plz help me review it again.

File: pkg/manager/member/tidb_member_manager_test.go (hunk 2 above)
Comment (KanShiori) [reply pkg/manager/member/tidb_member_manager_test.go:2457]: you can add a var to decide password.
```go
        var invalid bool
	patch := gomonkey.ApplyFunc(util.FixedLengthRandomPasswordBytes, func() []byte {
                if invalid {
                  invalid = true
                  return []byte("12\34") // return the invalid string firstly        
                }
		return []byte("1234") // return the invalid string firstly        
	})
```

**Review by KanShiori — APPROVED** [review]
Rest LGTM

File: pkg/manager/member/tidb_member_manager.go [hunk 3]
```diff
@@ -352,7 +352,14 @@ func (m *tidbMemberManager) buildRandomPasswordSecret(tc *v1alpha1.TidbCluster)
 			OwnerReferences: []metav1.OwnerReference{controller.GetOwnerRef(tc)},
 		},
 	}
-	password := util.FixedLengthRandomPasswordBytes()
+	var password []byte
+	for {
+		password = util.FixedLengthRandomPasswordBytes()
+		// check password not contain "\" character
+		if !strings.Contains(string(password), "\\") {
```
Comment (csuzhangxc) [inline pkg/manager/member/tidb_member_manager.go:359]: are there any more invalid chars?

**Review by csuzhangxc — APPROVED** [review]

File: pkg/manager/member/tidb_member_manager.go (hunk 3 above)
Comment (mikechengwei) [reply pkg/manager/member/tidb_member_manager.go:359]: There are no other characters found.
