### PR TITLE
sync health status of actual TiDB replicas instead of desired replicas

### LINKED ISSUE #1196: e2e: tidb stuck in upgrading
## Bug Report

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/operator_ghpr_e2e_test_kind/detail/operator_ghpr_e2e_test_kind/1047/pipeline/

controller log:

```
I1120 05:57:05.947161       1 utils.go:182] set e2e/cluster2-tidb partition to 2
I1120 05:57:05.980818       1 tidbcluster_control.go:68] TidbCluster: [e2e/cluster2] updated successfully
I1120 05:57:05.980921       1 tidb_cluster_controller.go:265] Finished syncing TidbCluster "e2e/cluster2" (40.133785ms)
I1120 05:57:05.980936       1 tidb_cluster_controller.go:250] TidbCluster: e2e/cluster2, still need sync: tidbcluster: [e2e/cluster2]'s tidb upgraded pod: [cluster2-tidb-2] is not ready, requeuing
```

tidb cluster:

```
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  annotations:
    pingcap.com/pd.cluster2-pd.sha: f3022ffb
    pingcap.com/tidb.cluster2-tidb.sha: 354df24b
    pingcap.com/tikv.cluster2-tikv.sha: c63b890b
  creationTimestamp: 2019-11-20T01:51:44Z
  generation: 1
  labels:
    app.kubernetes.io/component: tidb-cluster
    app.kubernetes.io/instance: cluster2
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: tidb-cluster
    helm.sh/chart: tidb-cluster-dev
  name: cluster2
  namespace: e2e
  resourceVersion: "95169"
  selfLink: /apis/pingcap.com/v1alpha1/namespaces/e2e/tidbclusters/cluster2
  uid: 4e2bfd7f-0b38-11ea-a151-0242ac110002
spec:
  pd:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: pd
                app.kubernetes.io/instance: cluster2
            namespaces:
            - e2e
            topologyKey: rack
          weight: 50
    image: pingcap/pd:v3.0.2
    imagePullPolicy: IfNotPresent
    limits:
      cpu: 1000m
      memory: 2Gi
    replicas: 1
    requests:
      cpu: 200m
      memory: 200Mi
      storage: 1Gi
    storageClassName: local-storage
  pvReclaimPolicy: Retain
  schedulerName: tidb-scheduler
  services:
  - name: pd
    type: ClusterIP
  tidb:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: tidb
                app.kubernetes.io/instance: cluster2
            namespaces:
            - e2e
            topologyKey: rack
          weight: 50
    image: pingcap/tidb:v3.0.2
    imagePullPolicy: IfNotPresent
    limits:
      cpu: 2000m
      memory: 4Gi
    maxFailoverCount: 3
    replicas: 2
    requests:
      cpu: 200m
      memory: 200Mi
    separateSlowLog: true
    slowLogTailer:
      image: busybox:1.26.2
      imagePullPolicy: IfNotPresent
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 20m
        memory: 5Mi
  tikv:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: tikv
                app.kubernetes.io/instance: cluster2
            namespaces:
            - e2e
            topologyKey: rack
          weight: 50
    image: pingcap/tikv:v3.0.2
    imagePullPolicy: IfNotPresent
    limits:
      cpu: 2000m
      memory: 4Gi
    maxFailoverCount: 3
    replicas: 3
    requests:
      cpu: 200m
      memory: 200Mi
      storage: 10Gi
    storageClassName: local-storage
  tikvPromGateway:
    image: ""
  timezone: UTC
status:
  clusterID: "6761200838373794682"
  pd:
    leader:
      clientURL: http://cluster2-pd-0.cluster2-pd-peer.e2e.svc:2379
      health: true
      id: "12968767987520570218"
      lastTransitionTime: 2019-11-20T01:52:28Z
      name: cluster2-pd-0
    members:
      cluster2-pd-0:
        clientURL: http://cluster2-pd-0.cluster2-pd-peer.e2e.svc:2379
        health: true
        id: "12968767987520570218"
        lastTransitionTime: 2019-11-20T01:52:28Z
        name: cluster2-pd-0
    phase: Normal
    statefulSet:
      collisionCount: 0
      currentReplicas: 1
      currentRevision: cluster2-pd-84c68cbd96
      observedGeneration: 1
      readyReplicas: 1
      replicas: 1
      updateRevision: cluster2-pd-84c68cbd96
      updatedReplicas: 1
    synced: true
  tidb:
    members:
      cluster2-tidb-0:
        health: true
        lastTransitionTime: 2019-11-20T01:59:26Z
        name: cluster2-tidb-0
        node: kind4-worker3
      cluster2-tidb-1:
        health: true
        lastTransitionTime: 2019-11-20T01:58:17Z
        name: cluster2-tidb-1
        node: kind4-worker4
    phase: Upgrade
    resignDDLOwnerRetryCount: 1
    statefulSet:
      collisionCount: 0
      currentReplicas: 2
      currentRevision: cluster2-tidb-5666744465
      observedGeneration: 3
      readyReplicas: 3
      replicas: 3
      updateRevision: cluster2-tidb-5986d9dd99
      updatedReplicas: 1
  tikv:
    phase: Normal
    statefulSet:
      collisionCount: 0
      currentReplicas: 3
      currentRevision: cluster2-tikv-7d56b4c4b8
      observedGeneration: 1
      readyReplicas: 3
      replicas: 3
      updateRevision: cluster2-tikv-7d56b4c4b8
      updatedReplicas: 3
    stores:
      "1":
        id: "1"
        ip: cluster2-tikv-0.cluster2-tikv-peer.e2e.svc
        lastHeartbeatTime: 2019-11-20T05:57:35Z
        lastTransitionTime: 2019-11-20T01:53:42Z
        leaderCount: 7
        podName: cluster2-tikv-0
        state: Up
      "4":
        id: "4"
        ip: cluster2-tikv-2.cluster2-tikv-peer.e2e.svc
        lastHeartbeatTime: 2019-11-20T05:57:33Z
        lastTransitionTime: 2019-11-20T01:54:17Z
        leaderCount: 6
        podName: cluster2-tikv-2
        state: Up
      "6":
        id: "6"
        ip: cluster2-tikv-1.cluster2-tikv-peer.e2e.svc
        lastHeartbeatTime: 2019-11-20T05:57:33Z
        lastTransitionTime: 2019-11-20T01:55:17Z
        leaderCount: 6
        podName: cluster2-tikv-1
        state: Up
    synced: true
```

sts: `kubectl -n e2e get asts cluster2-tidb -o yaml`

```
apiVersion: apps.pingcap.com/v1alpha1
kind: StatefulSet
metadata:
  annotations:
    pingcap.com/last-applied-configuration: '{"replicas":3,"selector":{"matchLabels":{"app.kubernetes.io/component":"tidb","app.kubernetes.io/instance":"cluster2","app.kubernetes.io/managed-by":"tidb-operator","app.kubernetes.io/name":"tidb-cluster"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app.kubernetes.io/component":"tidb","app.kubernetes.io/instance":"cluster2","app.kubernetes.io/managed-by":"tidb-operator","app.kubernetes.io/name":"tidb-cluster"},"annotations":{"prometheus.io/path":"/metrics","prometheus.io/port":"10080","prometheus.io/scrape":"true"}},"spec":{"volumes":[{"name":"annotations","downwardAPI":{"items":[{"path":"annotations","fieldRef":{"fieldPath":"metadata.annotations"}}]}},{"name":"config","configMap":{"name":"cluster2-tidb-354df24b","items":[{"key":"config-file","path":"tidb.toml"}]}},{"name":"startup-script","configMap":{"name":"cluster2-tidb-354df24b","items":[{"key":"startup-script","path":"tidb_start_script.sh"}]}},{"name":"slowlog","emptyDir":{}}],"containers":[{"name":"slowlog","image":"busybox:1.26.2","command":["sh","-c","touch
      /var/log/tidb/slowlog; tail -n0 -F /var/log/tidb/slowlog;"],"resources":{"limits":{"cpu":"100m","memory":"50Mi"},"requests":{"cpu":"20m","memory":"5Mi"}},"volumeMounts":[{"name":"slowlog","mountPath":"/var/log/tidb"}],"imagePullPolicy":"IfNotPresent"},{"name":"tidb","image":"pingcap/tidb:v3.0.2","command":["/bin/sh","/usr/local/bin/tidb_start_script.sh"],"ports":[{"name":"server","containerPort":4000,"protocol":"TCP"},{"name":"status","containerPort":10080,"protocol":"TCP"}],"env":[{"name":"CLUSTER_NAME","value":"cluster2"},{"name":"TZ","value":"UTC"},{"name":"BINLOG_ENABLED","value":"false"},{"name":"SLOW_LOG_FILE","value":"/var/log/tidb/slowlog"}],"resources":{"limits":{"cpu":"2","memory":"4Gi"},"requests":{"cpu":"200m","memory":"200Mi"}},"volumeMounts":[{"name":"annotations","readOnly":true,"mountPath":"/etc/podinfo"},{"name":"config","readOnly":true,"mountPath":"/etc/tidb"},{"name":"startup-script","readOnly":true,"mountPath":"/usr/local/bin"},{"name":"slowlog","mountPath":"/var/log/tidb"}],"readinessProbe":{"httpGet":{"path":"/status","port":10080,"scheme":"HTTP"},"initialDelaySeconds":10},"imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","dnsPolicy":"ClusterFirst","affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"weight":50,"podAffinityTerm":{"labelSelector":{"matchLabels":{"app.kubernetes.io/component":"tidb","app.kubernetes.io/instance":"cluster2"}},"namespaces":["e2e"],"topologyKey":"rack"}}]}},"schedulerName":"tidb-scheduler"}},"serviceName":"cluster2-tidb-peer","podManagementPolicy":"Parallel","updateStrategy":{"type":"RollingUpdate","rollingUpdate":{"partition":2}},"revisionHistoryLimit":10}'
  creationTimestamp: 2019-11-20T01:53:42Z
  generation: 3
  labels:
    app.kubernetes.io/component: tidb
    app.kubernetes.io/instance: cluster2
    app.kubernetes.io/managed-by: tidb-operator
    app.kubernetes.io/name: tidb-cluster
  name: cluster2-tidb
  namespace: e2e
  ownerReferences:
  - apiVersion: pingcap.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: TidbCluster
    name: cluster2
    uid: 4e2bfd7f-0b38-11ea-a151-0242ac110002
  resourceVersion: "47861"
  selfLink: /apis/apps.pingcap.com/v1alpha1/namespaces/e2e/statefulsets/cluster2-tidb
  uid: 94737072-0b38-11ea-a151-0242ac110002
spec:
  podManagementPolicy: Parallel
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: tidb
      app.kubernetes.io/instance: cluster2
      app.kubernetes.io/managed-by: tidb-operator
      app.kubernetes.io/name: tidb-cluster
  serviceName: cluster2-tidb-peer
  template:
    metadata:
      annotations:
        pingcap.com/last-applied-configuration: '{"volumes":[{"name":"annotations","downwardAPI":{"items":[{"path":"annotations","fieldRef":{"fieldPath":"metadata.annotations"}}]}},{"name":"config","configMap":{"name":"cluster2-tidb-354df24b","items":[{"key":"config-file","path":"tidb.toml"}]}},{"name":"startup-script","configMap":{"name":"cluster2-tidb-354df24b","items":[{"key":"startup-script","path":"tidb_start_script.sh"}]}},{"name":"slowlog","emptyDir":{}}],"containers":[{"name":"slowlog","image":"busybox:1.26.2","command":["sh","-c","touch
          /var/log/tidb/slowlog; tail -n0 -F /var/log/tidb/slowlog;"],"resources":{"limits":{"cpu":"100m","memory":"50Mi"},"requests":{"cpu":"20m","memory":"5Mi"}},"volumeMounts":[{"name":"slowlog","mountPath":"/var/log/tidb"}],"imagePullPolicy":"IfNotPresent"},{"name":"tidb","image":"pingcap/tidb:v3.0.2","command":["/bin/sh","/usr/local/bin/tidb_start_script.sh"],"ports":[{"name":"server","containerPort":4000,"protocol":"TCP"},{"name":"status","containerPort":10080,"protocol":"TCP"}],"env":[{"name":"CLUSTER_NAME","value":"cluster2"},{"name":"TZ","value":"UTC"},{"name":"BINLOG_ENABLED","value":"false"},{"name":"SLOW_LOG_FILE","value":"/var/log/tidb/slowlog"}],"resources":{"limits":{"cpu":"2","memory":"4Gi"},"requests":{"cpu":"200m","memory":"200Mi"}},"volumeMounts":[{"name":"annotations","readOnly":true,"mountPath":"/etc/podinfo"},{"name":"config","readOnly":true,"mountPath":"/etc/tidb"},{"name":"startup-script","readOnly":true,"mountPath":"/usr/local/bin"},{"name":"slowlog","mountPath":"/var/log/tidb"}],"readinessProbe":{"httpGet":{"path":"/status","port":10080,"scheme":"HTTP"},"initialDelaySeconds":10},"imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","dnsPolicy":"ClusterFirst","affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"weight":50,"podAffinityTerm":{"labelSelector":{"matchLabels":{"app.kubernetes.io/component":"tidb","app.kubernetes.io/instance":"cluster2"}},"namespaces":["e2e"],"topologyKey":"rack"}}]}},"schedulerName":"tidb-scheduler"}'
        prometheus.io/path: /metrics
        prometheus.io/port: "10080"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: tidb
        app.kubernetes.io/instance: cluster2
        app.kubernetes.io/managed-by: tidb-operator
        app.kubernetes.io/name: tidb-cluster
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: tidb
                  app.kubernetes.io/instance: cluster2
              namespaces:
              - e2e
              topologyKey: rack
            weight: 50
      containers:
      - command:
        - sh
        - -c
        - touch /var/log/tidb/slowlog; tail -n0 -F /var/log/tidb/slowlog;
        image: busybox:1.26.2
        imagePullPolicy: IfNotPresent
        name: slowlog
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 20m
            memory: 5Mi
        volumeMounts:
        - mountPath: /var/log/tidb
          name: slowlog
      - command:
        - /bin/sh
        - /usr/local/bin/tidb_start_script.sh
        env:
        - name: CLUSTER_NAME
          value: cluster2
        - name: TZ
          value: UTC
        - name: BINLOG_ENABLED
          value: "false"
        - name: SLOW_LOG_FILE
          value: /var/log/tidb/slowlog
        image: pingcap/tidb:v3.0.2
        imagePullPolicy: IfNotPresent
        name: tidb
        ports:
        - containerPort: 4000
          name: server
          protocol: TCP
        - containerPort: 10080
          name: status
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /status
            port: 10080
            scheme: HTTP
          initialDelaySeconds: 10
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 200m
            memory: 200Mi
        volumeMounts:
        - mountPath: /etc/podinfo
          name: annotations
          readOnly: true
        - mountPath: /etc/tidb
          name: config
          readOnly: true
        - mountPath: /usr/local/bin
          name: startup-script
          readOnly: true
        - mountPath: /var/log/tidb
          name: slowlog
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: tidb-scheduler
      volumes:
      - downwardAPI:
          items:
          - fieldRef:
              fieldPath: metadata.annotations
            path: annotations
        name: annotations
      - configMap:
          items:
          - key: config-file
            path: tidb.toml
          name: cluster2-tidb-354df24b
        name: config
      - configMap:
          items:
          - key: startup-script
            path: tidb_start_script.sh
          name: cluster2-tidb-354df24b
        name: startup-script
      - emptyDir: {}
        name: slowlog
  updateStrategy:
    rollingUpdate:
      partition: 2
    type: RollingUpdate
status:
  collisionCount: 0
  currentReplicas: 2
  currentRevision: cluster2-tidb-5666744465
  observedGeneration: 3
  readyReplicas: 3
  replicas: 3
  updateRevision: cluster2-tidb-5986d9dd99
  updatedReplicas: 1
```

### PR DESCRIPTION
**Pull request by cofyc**
### What problem does this PR solve? 

fixes #1196 

### What is changed and how does it work?

- rename `<TiDB/PD/TiKV>RealReplicas` to `<TiDB/PD/TiKV>DesiredReplicas`, because tc.`<TiDB/PD/TiKV>.Replicas + len(tc.Status.<TiDB/PD/TiKV>.FailureMembers)` is the desired replicas
- add `<TiDB/PD/TiKV>ActualReplicas` 
- use `TiDBActualReplicas()` in health status sync

### Check List 

Tests 

 - Unit test
 - E2E test

### CODE REVIEW

File: pkg/apis/pingcap/v1alpha1/tidbcluster.go [hunk 1]
```diff
@@ -59,16 +59,24 @@ func (tc *TidbCluster) PDAutoFailovering() bool {
 	return false
 }
 
-func (tc *TidbCluster) PDRealReplicas() int32 {
+func (tc *TidbCluster) PDDesiredReplicas() int32 {
```
Comment (cofyc) [inline pkg/apis/pingcap/v1alpha1/tidbcluster.go]: I prefer to rename `<TiDB/PD/TiKV>RealReplicas` to `<TiDB/PD/TiKV>DesiredReplicas`, because `tc.<TiDB/PD/TiKV>.Replicas + tc.Status.<TiDB/PD/TiKV>.FailureMembers` is the desired replicas.

File: pkg/apis/pingcap/v1alpha1/tidbcluster.go [hunk 2]
```diff
@@ -59,16 +59,24 @@ func (tc *TidbCluster) PDAutoFailovering() bool {
...
 	return tc.Spec.PD.Replicas + int32(len(tc.Status.PD.FailureMembers))
 }
 
+func (tc *TidbCluster) PDActualReplicas() int32 {
```
Comment (cofyc) [inline pkg/apis/pingcap/v1alpha1/tidbcluster.go]: We use sts to manage pods, so the status of the replica of sts is actual replicas.

File: pkg/controller/tidb_control.go [hunk 3]
```diff
@@ -85,7 +85,7 @@ func (tdc *defaultTiDBControl) GetHealth(tc *v1alpha1.TidbCluster) map[string]bo
 		return result
 	}
 
-	for i := 0; i < int(tc.TiDBRealReplicas()); i++ {
+	for i := 0; i < int(tc.TiDBActualReplicas()); i++ {
```
Comment (cofyc) [inline pkg/controller/tidb_control.go]: Sync the health status of all actual replicas instead of desired replicas.

File: pkg/apis/pingcap/v1alpha1/tidbcluster.go (hunk 1 above)
Comment (onlymellb) [reply pkg/apis/pingcap/v1alpha1/tidbcluster.go]: I think this name should not be modified. The desired replicas represent the replicas set by the user. When a failover occurs, the actual replicas will be higher than the user settings.

Comment (cofyc) [reply pkg/apis/pingcap/v1alpha1/tidbcluster.go]: len(failoverMembers) is only increased when the user enabled auto-failover, so the desired replicas is what the user want

Comment (Yisaer) [reply pkg/apis/pingcap/v1alpha1/tidbcluster.go]: > I think this name should not be modified. The desired replicas represent the replicas set by the user. When a failover occurs, the actual replicas will be higher than the user settings.

I agreed so.

Comment (cofyc) [reply pkg/apis/pingcap/v1alpha1/tidbcluster.go]: as suggested by @onlymellb , I've added statefulset prefix (`sts`) to indicate that these are desired/actual replicas of stateful sets we are managing.
cc @weekface

File: pkg/apis/pingcap/v1alpha1/tidbcluster.go [hunk 4]
```diff
@@ -59,16 +59,24 @@ func (tc *TidbCluster) PDAutoFailovering() bool {
...
+}
+
 func (tc *TidbCluster) TiKVAllPodsStarted() bool {
-	return tc.TiKVRealReplicas() == tc.Status.TiKV.StatefulSet.Replicas
+	return tc.TiKVDesirdReplicas() == tc.TiKVStsActualReplicas()
 }
 
 func (tc *TidbCluster) TiKVAllStoresReady() bool {
-	if int(tc.TiKVRealReplicas()) != len(tc.Status.TiKV.Stores) {
+	if int(tc.TiKVDesirdReplicas()) != len(tc.Status.TiKV.Stores) {
```
Comment (DanielZhangQD) [inline pkg/apis/pingcap/v1alpha1/tidbcluster.go]: Add `Sts`?

Comment (cofyc) [reply pkg/apis/pingcap/v1alpha1/tidbcluster.go]: thanks for catching this, I missed this.

Comment (cofyc) [reply pkg/apis/pingcap/v1alpha1/tidbcluster.go]: fixed

**Comment by cofyc** [comment]
Thanks!
