### PR TITLE
Retain last applied pod template to keep backward-compatibility

### LINKED ISSUE #1475: Update statefulset should retain the last-applied-configuration
## Bug Report

#1414 will trigger rolling-update of legacy cluster because the annotations of the old cluster are totally overridden:

Before:
```
        annotations:
          prometheus.io/path: /metrics
          prometheus.io/port: "2379"
          prometheus.io/scrape: "true"
```

After upgrading operator:
```
        annotations:
          pingcap.com/last-applied-configuration: '{"volumes"....'
          prometheus.io/path: /metrics
          prometheus.io/port: "2379"
          prometheus.io/scrape: "true"
```
Though we do not set this annotation anymore, we should keep this during update to keep the backward compatibility.

### PR DESCRIPTION
**Pull request by aylei**
Signed-off-by: Aylei <rayingecho@gmail.com>

### What problem does this PR solve? 
close #1475 
### What is changed and how does it work?
Now the `last-applied-config` annotation of statefulset's PodTemplate will be retained during update to keep the backward-compatibility.

In addition, we need #1440 to help us prevent such issues.
### Check List 

Tests 

 - Unit test
 - E2E test

### Does this PR introduce a user-facing change?:

```release-note
Retain last-applied-config of StatefulSet's `PodTemplate` during updates to keep backward compatibility.
```

### CODE REVIEW

**Comment by aylei** [comment]
@weekface @cofyc @DanielZhangQD @Yisaer PTAL

File: pkg/manager/member/utils.go [hunk 1]
```diff
@@ -262,3 +263,36 @@ func MapContainers(podSpec *corev1.PodSpec) map[string]corev1.Container {
...
+		// Retain the deprecated last applied pod template annotation for backward compatibility
+		var podConfig string
+		var hasPodConfig bool
+		if oldSet.Spec.Template.Annotations != nil {
+			podConfig, hasPodConfig = oldSet.Spec.Template.Annotations[LastAppliedConfigAnnotation]
+		}
+		set.Spec.Template = newSet.Spec.Template
+		if hasPodConfig {
+			set.Spec.Template.Annotations[LastAppliedConfigAnnotation] = podConfig
+		}
```
Comment (cofyc) [inline pkg/manager/member/utils.go]: `SetStatefulSetLastAppliedConfigAnnotation` is used to set last-applied-config annotation(s), move the `Spec.Template.Annotations[LastAppliedConfigAnnotation]` backward compatility logic into it?

Comment (aylei) [reply pkg/manager/member/utils.go]: It will change the interface of this method (which needs the old annotation)
