### PR TITLE
br: fix backup stuck due to init pod creating stuck

### LINKED ISSUE #5456: backup is stuck when the init pod creating stuck and exceed ttl
## Bug Report

**What version of TiDB Operator are you using?**

v1.5

**What did you do?**

I create a `VolumeBackup`, but the init pod creating is stuck. The init pod is always in `PodInitializing` state. After 15 minutes, it's deleted by job ttl.

**What did you expect to see?**

the `VolumeBackup` is failed

**What did you see instead?**

the `VolumeBackup` is still running.

### PR DESCRIPTION
**Pull request by WangLe1321**
### What problem does this PR solve?

Closes #5456 

### Code changes

- [ ] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [ ] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

File: pkg/backup/backup/backup_manager.go [hunk 1]
```diff
@@ -244,7 +244,7 @@ func (bm *backupManager) checkVolumeBackupInitializeJobRunning(backup *v1alpha1.
 		// all the volume snapshots has created
 		return nil
 	}
-	if !v1alpha1.IsVolumeBackupInitialized(backup) || v1alpha1.IsVolumeBackupInitializeFailed(backup) {
+	if v1alpha1.IsVolumeBackupInitializeFailed(backup) {
```
Comment (nkg-) [inline pkg/backup/backup/backup_manager.go:247]: Noob question. checkVolumeBackupInitializeJobRunning is used to detect init job failures. Based on the "err" returned from this function. IF IsVolumeBackupInitializeFailed == true, then why we return nil, rather than returning an error.

Comment (nkg-) [inline pkg/backup/backup/backup_manager.go:247]: Let me understand the removal of IsVolumeBackupInitialized. Now if the init job is stuck and eventually ttled, then  this method won't find the job, and return "init job deleted before ..." error here https://github.com/pingcap/tidb-operator/blob/6ec83b038432fd5c64458e883d7c12d02e83b5d3/pkg/backup/backup/backup_manager.go#L268. Right?

Comment (WangLe1321) [reply pkg/backup/backup/backup_manager.go]: No, the job still exists but it has failed status due to ttl. So we will find job failed and set backup failed here https://github.com/pingcap/tidb-operator/blob/6ec83b038432fd5c64458e883d7c12d02e83b5d3/pkg/backup/backup/backup_manager.go#L292

In addition, I verified the change by unit test. We can't remove the condition directly because in the first reconcile, the backup job is not created and we will get a 'not found' error. So I modified the condition.

Comment (WangLe1321) [reply pkg/backup/backup/backup_manager.go]: Because the aim of this function is to detect init job failure and set backup CR to `IsVolumeBackupInitializeFailed`. So if `IsVolumeBackupInitializeFailed == true`, it means we don't need this check. If we return error here, it can block the main logic of the backup controller.

**Review by BornChanger — APPROVED** [review]

**Review by BornChanger — APPROVED** [review]
