### PR TITLE
Fixing volume tagging

### LINKED ISSUE #5505: If there is a PV with the same name (released status) in the namespace, it will cause the restore to fail
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**
1. there is a PV with the same name with restore tc (released status) in the namespace
2. do volume restore

**What did you expect to see?**
1. restore success
**What did you see instead?**
1. restore failed
2. 
img_v3_026s_7e12385c-e9dd-463f-a4d6-2ffb5f31c03g
img_v3_026s_73e8f8aa-d8f0-4456-8fe4-dd8367c7992g
img_v3_026s_6a5e2f89-eb75-4726-9c95-6111f04d465g

### PR DESCRIPTION
**Pull request by BornChanger**
### What problem does this PR solve?

Closes #5505 

### What is changed and how does it work?

1. Add tags to valid PVs in the cluster
2. Add tag of name of namespace

### Code changes

- [X] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [x] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

File: pkg/backup/snapshotter/snapshotter_aws.go [hunk 1]
```diff
@@ -102,15 +103,12 @@ func (s *AWSSnapshotter) AddVolumeTags(pvs []*corev1.PersistentVolume) error {
...
-
 		tags := make(map[string]string)
-		tags[PVCTagKey] = pvcName
-		tags[PodTagKey] = podName
+		tags[PVCTagKey] = pv.GetName()
+		tags[PodTagKey] = pv.GetAnnotations()[label.AnnPodNameKey]
+		tags[PodNSTagKey] = pv.GetAnnotations()[label.NamespaceLabelKey]
 
-		resourcesTags[volId] = tags
+		resourcesTags[pv.Spec.CSI.VolumeHandle] = tags
```
Comment (WangLe1321) [inline pkg/backup/snapshotter/snapshotter_aws.go:111]: you can get volume id by `pv.Annotations[constants.AnnRestoredVolumeID]`. `pv.Spec.CSI.VolumeHandle` may be empty. you can see `Snapshotter.GetVolumeID` and `Snapshotter.SetVolumeID` methods.

Comment (BornChanger) [reply pkg/backup/snapshotter/snapshotter_aws.go]: done

**Review by WangLe1321 — APPROVED** [review]
