### PR TITLE
backup: fix issue 1657

### LINKED ISSUE #1657: The failure message in backup status is overwhelming
## Bug Report

**What version of TiDB Operator are you using?**

`2e566a0379b47eeedaac72897daedbb97515920c`

**What did you do?**

Took a backup using `br` and failed, inspect the status of `backup` object to reason why.

**What did you expect to see?**
A reasonable error reason in  `.status.message`

**What did you see instead?**
An overwhelming error message:

[status.tar.gz](https://github.com/pingcap/tidb-operator/files/4174035/status.tar.gz)

### PR DESCRIPTION
**Pull request by shuijing198799**
### What problem does this PR solve? 
fixes #1657
### What is changed and how does it work?
create a stdout pipe from the exec process, and read the pipe message in a for loop, If the output meesage with ERROR, add to the backup status message information
### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)
It seems the log will output intime and the backup status messsage is 
```
  status:
    backupPath: ""
    backupSize: 0
    commitTs: ""
    conditions:
    - lastTransitionTime: "2020-03-30T12:14:02Z"
      message: ""
      reason: ""
      status: "True"
      type: Scheduled
    - lastTransitionTime: "2020-03-30T12:14:03Z"
      message: ""
      reason: ""
      status: "True"
      type: Running
    - lastTransitionTime: "2020-03-30T12:14:36Z"
      message: "cluster cluster/sa-backup-s3, wait pipe message failed, errMsg [2020/03/30
        12:14:36.196 +00:00] [ERROR] [push.go:106] [\"backup occur unknown error\"]
        [error=\"Io(Custom { kind: Other, error: \\\"failed to put object Couldn\\\\'t
        find AWS credentials in environment, credentials file, or IAM role.\\\" })\"]
        [stack=\"github.com/pingcap/log.Error\\n\\t/go/pkg/mod/github.com/pingcap/log@v0.0.0-20200117041106-d28c14d3b1cd/global.go:42\\ngithub.com/pingcap/br/pkg/backup.(*pushDown).pushBackup\\n\\t/home/jenkins/agent/workspace/build_br_master/go/src/github.com/pingcap/br/pkg/backup/push.go:106\\ngithub.com/pingcap/br/pkg/backup.(*Client).backupRange\\n\\t/home/jenkins/agent/workspace/build_br_master/go/src/github.com/pingcap/br/pkg/backup/client.go:404\\ngithub.com/pingcap/br/pkg/backup.(*Client).BackupRanges.func2\\n\\t/home/jenkins/agent/workspace/build_br_master/go/src/github.com/pingcap/br/pkg/backup/client.go:316\"]\n\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0,
        err: exit status 1"
      reason: BackupDataToRemoteFailed
      status: "True"
      type: Failed
    timeCompleted: null
    timeStarted: null
```
Code changes

 - Has Go code change

### CODE REVIEW

**Comment by cofyc** [comment]
btw, you can use [these keywords](https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords#about-issue-references) in your PR to close issue automatically

**Comment by cofyc** [comment]
should this be cherry-picked into 1.1?

**Comment by shuijing198799** [comment]
> should this be cherry-picked into 1.1?

**Comment by shuijing198799** [comment]
> should this be cherry-picked into 1.1?

I discuss with daniel, this is not merge to 1.1

**Comment by cofyc** [comment]
but it seems a bug fix?

**Comment by shuijing198799** [comment]
> but it seems a bug fix. should it be merged before 1.1 GA?

this just fix the back/restore can't output log intime and If it is failed, the error message container all of info log. not very important

**Comment by DanielZhangQD** [comment]
> should this be cherry-picked into 1.1?

Yes, this needs to be in 1.1.

File: cmd/backup-manager/app/backup/backup.go [hunk 1]
```diff
@@ -63,11 +64,35 @@ func (bo *Options) backupData(backup *v1alpha1.Backup) (string, error) {
...
+	cmd.Stderr = cmd.Stdout
+	stdOut, err := cmd.StdoutPipe()
 	if err != nil {
-		return remotePath, fmt.Errorf("cluster %s, execute br command %v failed, output: %s, err: %v", bo, fullArgs, string(output), err)
+		return remotePath, fmt.Errorf("cluster %s, create stdout pipe failed, err: %v", bo, err)
 	}
-	klog.Infof("Backup data for cluster %s successfully, output: %s", bo, string(output))
+	err = cmd.Start()
+	if err != nil {
+		return remotePath, fmt.Errorf("cluster %s, execute br command failed, output: %s, err: %v", bo, fullArgs, err)
```
Comment (DanielZhangQD) [inline cmd/backup-manager/app/backup/backup.go]: No parameter for output.

File: cmd/backup-manager/app/backup/backup.go [hunk 2]
```diff
@@ -63,11 +64,35 @@ func (bo *Options) backupData(backup *v1alpha1.Backup) (string, error) {
...
+	}
+	var tmpOutput, errMsg string
+	for {
+		tmp := make([]byte, 1024)
+		_, err := stdOut.Read(tmp)
+		tmpOutput = string(tmp)
+		if strings.Contains(tmpOutput, "[ERROR]") {
+			errMsg += tmpOutput
+		}
+		klog.Infof(tmpOutput)
```
Comment (DanielZhangQD) [inline cmd/backup-manager/app/backup/backup.go]: We have to handle the new line of `tmpOutput`, otherwise, there will be an empty line in logs.

File: cmd/backup-manager/app/restore/restore.go [hunk 3]
```diff
@@ -57,11 +58,34 @@ func (ro *Options) restoreData(restore *v1alpha1.Restore) error {
...
+	cmd.Stderr = cmd.Stdout
+	stdOut, err := cmd.StdoutPipe()
 	if err != nil {
-		return fmt.Errorf("cluster %s, execute br command %v failed, output: %s, err: %v", ro, fullArgs, string(output), err)
+		return fmt.Errorf("cluster %s, create stdout pipe failed, err: %v", ro, err)
 	}
-	klog.Infof("Restore data for cluster %s successfully, output: %s", ro, string(output))
+	err = cmd.Start()
+	if err != nil {
+		return fmt.Errorf("cluster %s, execute br command failed, output: %s, err: %v", ro, fullArgs, err)
```
Comment (DanielZhangQD) [inline cmd/backup-manager/app/restore/restore.go]: ditto

File: cmd/backup-manager/app/restore/restore.go [hunk 4]
```diff
@@ -57,11 +58,34 @@ func (ro *Options) restoreData(restore *v1alpha1.Restore) error {
...
+	}
+	var tmpOutput, errMsg string
+	for {
+		tmp := make([]byte, 1024)
+		_, err := stdOut.Read(tmp)
+		tmpOutput = string(tmp)
+		if strings.Contains(tmpOutput, "[ERROR]") {
+			errMsg += tmpOutput
+		}
+		klog.Infof(tmpOutput)
```
Comment (DanielZhangQD) [inline cmd/backup-manager/app/restore/restore.go]: ditto

File: cmd/backup-manager/app/backup/backup.go (hunk 1 above)
Comment (shuijing198799) [reply cmd/backup-manager/app/backup/backup.go]: this line just output why launch process failed, I think need no output parameter

File: cmd/backup-manager/app/backup/backup.go (hunk 2 above)
Comment (shuijing198799) [reply cmd/backup-manager/app/backup/backup.go]: done

File: cmd/backup-manager/app/restore/restore.go (hunk 4 above)
Comment (shuijing198799) [reply cmd/backup-manager/app/restore/restore.go]: done

File: cmd/backup-manager/app/restore/restore.go (hunk 3 above)
Comment (shuijing198799) [reply cmd/backup-manager/app/restore/restore.go]: done
