### PR TITLE
auto clean secrets when cluster is deleted

### LINKED ISSUE #1154: Cert secrets are not deleted when the cluster are deleted
## Bug Report

When enabling TLS for TiDB cluster, the cert secrets are not deleted when the cluster is deleted.

### PR DESCRIPTION
**Pull request by tennix**
### What problem does this PR solve? 

This PR closes #1154 
### What is changed and how does it work?

Add TidbCluster `OwnerReference` to the cert secrets, so when the TidbCluster is deleted, the secrets are deleted automatically.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Create a cluster with tls enabled, when the cluster is deleted, the secrets are deleted automatically.

Code changes

 - Has Go code change

Side effects

None

Related changes

None

### Does this PR introduce a user-facing change?:
 
 ```release-note
None
 ```

### CODE REVIEW

File: pkg/controller/secret_control.go [hunk 1]
```diff
@@ -30,7 +32,7 @@ import (
 
 // SecretControlInterface manages certificates used by TiDB clusters
 type SecretControlInterface interface {
-	Create(certOpts *TiDBClusterCertOptions, cert []byte, key []byte) error
+	Create(tc *v1alpha1.TidbCluster, certOpts *TiDBClusterCertOptions, cert []byte, key []byte) error
```
Comment (aylei) [inline pkg/controller/secret_control.go]: This API is not generic, I prefer passing owner reference, which abstracts the real owner away

File: pkg/controller/cert_control.go [hunk 2]
```diff
@@ -42,7 +44,7 @@ type TiDBClusterCertOptions struct {
 
 // CertControlInterface manages certificates used by TiDB clusters
 type CertControlInterface interface {
-	Create(certOpts *TiDBClusterCertOptions) error
+	Create(tc *v1alpha1.TidbCluster, certOpts *TiDBClusterCertOptions) error
```
Comment (aylei) [inline pkg/controller/cert_control.go]: ditto
