### PR TITLE
fix: add a new check for encryption during the volume snapshot restore

### LINKED ISSUE #4913: br: add a new check for tikv encryption during the volume-snapshot restore
## Bug Report

**What version of Kubernetes are you using?**
`[root@kvm-dev kms]# kubectl version
Client Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.6-eks-7d68063", GitCommit:"f24e667e49fb137336f7b064dba897beed639bad", GitTreeState:"clean", BuildDate:"2022-02-23T19:32:14Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.16-eks-ffeb93d", GitCommit:"52e500d139bdef42fbc4540c357f0565c7867a81", GitTreeState:"clean", BuildDate:"2022-11-29T18:41:42Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}`

**What version of TiDB Operator are you using?**
v1.5.alpha.5

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
NA

**What's the status of the TiDB cluster pods?**

**What did you do?**
volume snapshot restore support 

- both backup and restore with the same encryption
- backup without encryption and restore has encryption

volume snapshot restore does not support

- backup has encryption and restore has not

**What did you expect to see?**
 when volume snapshot does not support scenario happened, do not launch the restore to save the resource

**What did you see instead?**
restore is happened, and finally failure at the very end of restore stage

### PR DESCRIPTION
**Pull request by fengou1**
### What problem does this PR solve?
Add a new check for volume snapshot restore

Closes #4913 
### Code changes

- [ ] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [x] Unit test 
- [ ] E2E test 
- [x] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

File: pkg/backup/restore/restore_manager.go [hunk 1]
```diff
@@ -268,6 +268,63 @@ func (rm *restoreManager) validateRestore(r *v1alpha1.Restore, tc *v1alpha1.Tidb
...
+//	backup has encryption and restore has not
+func (rm *restoreManager) checkTiKVEncryption(r *v1alpha1.Restore, tc *v1alpha1.TidbCluster) error {
+	backupConfig, reason, err := rm.readTiKVConfigFromBackupMeta(r)
+	if err != nil {
+		klog.Errorf("read tiflash replica failure with reason %s", reason)
+		return err
+	}
+
+	// check encryption is enabled
+	if v := backupConfig.Get("security.encryption.data-encryption-method"); v != nil {
```
Comment (WangLe1321) [inline pkg/backup/restore/restore_manager.go:294]: if `v == nil`, it can indicate that there is no encryption in backup. I think we can `return nil` directly.

File: pkg/backup/restore/restore_manager.go [hunk 2]
```diff
@@ -268,6 +268,63 @@ func (rm *restoreManager) validateRestore(r *v1alpha1.Restore, tc *v1alpha1.Tidb
...
+			}
+		}
+	}
+
+	// if backup tikv configured encryption, restore require tc to have the same encryption configured.
+	// since master key is is unique, only check master key id is enough. e.g. https://docs.aws.amazon.com/kms/latest/cryptographic-details/basic-concepts.html
+	backupMasterKey := backupConfig.Get("security.encryption.master-key.key-id")
+	if backupMasterKey != nil {
+		config := tc.Spec.TiKV.Config
+		if config == nil {
```
Comment (WangLe1321) [inline pkg/backup/restore/restore_manager.go:315]: We don't need validate config twice.

File: pkg/backup/restore/restore_manager.go [hunk 3]
```diff
@@ -284,6 +341,19 @@ func (rm *restoreManager) readTiFlashReplicasFromBackupMeta(r *v1alpha1.Restore)
...
+	metaInfo, err := backuputil.GetVolSnapBackupMetaData(r, rm.deps.SecretLister)
+	if err != nil {
+		return nil, "GetVolSnapBackupMetaData failed", err
+	}
+
+	if metaInfo.KubernetesMeta.TiDBCluster.Spec.TiKV == nil {
+		return nil, "BackupMetaDoesnotContainTiKV", fmt.Errorf("TiKV is not configure in backup")
+	}
+
+	return metaInfo.KubernetesMeta.TiDBCluster.Spec.TiKV.Config, "", nil
```
Comment (WangLe1321) [inline pkg/backup/restore/restore_manager.go:354]: Should we also check whether `metaInfo.KubernetesMeta.TiDBCluster.Spec.TiKV.Config == nil`?

Comment (fengou1) [reply pkg/backup/restore/restore_manager.go:360]: fixed in https://github.com/pingcap/tidb-operator/pull/4914/commits/6a26fcafb80564c25d3d12e057ae19d0100ebe51

File: pkg/backup/restore/restore_manager.go (hunk 1 above)
Comment (fengou1) [reply pkg/backup/restore/restore_manager.go]: https://github.com/pingcap/tidb-operator/pull/4914/commits/6a26fcafb80564c25d3d12e057ae19d0100ebe51

File: pkg/backup/restore/restore_manager.go [hunk 4]
```diff
@@ -268,6 +268,63 @@ func (rm *restoreManager) validateRestore(r *v1alpha1.Restore, tc *v1alpha1.Tidb
...
+
+	// check encryption is enabled
+	if v := backupConfig.Get("security.encryption.data-encryption-method"); v != nil {
+		config := tc.Spec.TiKV.Config
+		if config == nil {
+			return fmt.Errorf("TiKV encryption config missmatched, backup configured TiKV encription, however, restore tc.spec.tikv.config doesn't contains encryption, please check TiKV encryption config. e.g. download s3 backupmeta, check kubernetes.crd_tidb_cluster.spec, and then edit restore tc.")
+		}
+
+		encryptMethod := v.Interface()
+		if encryptMethod != "plaintext" {
```
[the remark this answers is not in the document]
Comment (fengou1) [reply pkg/backup/restore/restore_manager.go]: https://github.com/pingcap/tidb-operator/pull/4914/commits/6a26fcafb80564c25d3d12e057ae19d0100ebe51

**Review by WangLe1321 — APPROVED** [review]

**Review by WizardXiao — APPROVED** [review]
