### PR TITLE
Avoid printing too many error logs in pod controller

### LINKED ISSUE #4447: Multiple Sets of TiDB Operator bug: fetching pods belongs to other tidb-operator's selector
## Bug Report

**What version of Kubernetes are you using?**

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:41:51Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:33:08Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of TiDB Operator are you using?**

v1.3.1

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

update tidb-operator from v1.2.3 to v.1.3.1.

```
controllerManager:
  selector:
    - managed-by==utf
  # - canary-release=v1
  # - k1==v1
  # - k2!=v2
```

**What did you expect to see?**

No ERRORS

**What did you see instead?**

Lots of errors and the tidb-operator sync pod belongs to other selector.

```
E0225 09:14:31.348265       1 pod_control.go:139] TidbCluster pod: tipocket-ledger1-1645646400/tipocket-ledger1-tikv-2, sync failed failed to get tc "tipocket-ledger1-1645646400/tipocket-ledger1": [tidbcluster.pingcap.com](http://tidbcluster.pingcap.com/) "tipocket-ledger1" not found, requeuing
E0225 09:14:31.448307       1 pod_control.go:139] TidbCluster pod: acct-5rzsc/tc-tikv-12, sync failed failed to get tc "acct-5rzsc/tc": [tidbcluster.pingcap.com](http://tidbcluster.pingcap.com/) "tc" not found, requeuing
E0225 09:14:31.548264       1 pod_control.go:139] TidbCluster pod: acct-5rzsc/tc-tikv-5, sync failed failed to get tc "acct-5rzsc/tc": [tidbcluster.pingcap.com](http://tidbcluster.pingcap.com/) "tc" not found, requeuing
E0225 09:14:31.648304       1 pod_control.go:139] TidbCluster pod: acct-5rzsc/tc-tikv-6, sync failed failed to get tc "acct-5rzsc/tc": [tidbcluster.pingcap.com](http://tidbcluster.pingcap.com/) "tc" not found, requeuing
E0225 09:14:31.748269       1 pod_control.go:139] TidbCluster pod: endless-htap-misc-master-tps-604667-1-870/tc-tikv-1, sync failed failed to get tc "endless-htap-misc-master-tps-604667-1-870/tc": [tidbcluster.pingcap.com](http://tidbcluster.pingcap.com/) "tc" not found, requeuing
E0225 09:14:31.848290       1 pod_control.go:139] TidbCluster pod: test-infra/tcms-tikv-5, sync failed failed to get tc "test-infra/tcms": [tidbcluster.pingcap.com](http://tidbcluster.pingcap.com/) "tcms" not found, requeuing
E0225 09:14:31.948293       1 pod_con
```

### PR DESCRIPTION
**Pull request by KanShiori**
### What problem does this PR solve?

Close #4447
### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [x] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

File: pkg/controller/tidbcluster/pod_control.go [hunk 1]
```diff
@@ -179,6 +179,13 @@ func (c *PodController) sync(key string) (reconcile.Result, error) {
 		return reconcile.Result{}, nil
 	}
 
+	tc, err := c.deps.TiDBClusterLister.TidbClusters(ns).Get(tcName)
```
Comment (just1900) [inline pkg/controller/tidbcluster/pod_control.go:182]: IMHO, this will still print the error logs, the root cause of #4447 here is that we are watching all pods rather than pods that are filtered out by the lable selector.

Comment (KanShiori) [reply pkg/controller/tidbcluster/pod_control.go:182]: Agree, but unfortunately, pods don't contain labels that are set by `controllerManager.selector`.

Comment (just1900) [reply pkg/controller/tidbcluster/pod_control.go:182]: Maybe change `deps.KubeInformerFactory` to `deps.LabelFilterKubeInformerFactory` will work
https://github.com/pingcap/tidb-operator/blob/c09574aa38346ab52ead0498bd6cf282a4f58abc/pkg/controller/tidbcluster/pod_control.go#L67
or change the podLister in deps directlly?
https://github.com/pingcap/tidb-operator/blob/c09574aa38346ab52ead0498bd6cf282a4f58abc/pkg/controller/dependences.go#L330

Comment (just1900) [reply pkg/controller/tidbcluster/pod_control.go:182]: I see what you mean, that doesn't help. : (

Comment (KanShiori) [reply pkg/controller/tidbcluster/pod_control.go:182]: If don't need to watch Pods, we can list TC firstly and find their Pods. WDYT? @july2993

Comment (july2993) [reply pkg/controller/tidbcluster/pod_control.go:182]: The annotation is added on the pod to trigger a restart, to be responsive we need to watch pod.
how about

Comment (july2993) [reply pkg/controller/tidbcluster/pod_control.go:182]: This can avoid the issue of #4447, but we should just return nil if and only the error is NotFound because the tc may already be deleted when we handle the pod.
And seems we should ignore the pod that belong to tc with labels not match our `controllerManager.selector`

Comment (KanShiori) [reply pkg/controller/tidbcluster/pod_control.go:182]: `c.deps.TiDBClusterLister` have filter the tc not match `controllerManager.selector`

Comment (just1900) [reply pkg/controller/tidbcluster/pod_control.go:182]: > This can avoid the issue of #4447, but we should just return nil if and only the error is NotFound because the tc may already be deleted when we handle the pod.

It makes sense to me, we do nothing if `deps.TiDBClusterLister` returns NotFoundError, which means either tc is deleted or tc is not match `selector`.

Comment (july2993) [reply pkg/controller/tidbcluster/pod_control.go:182]: then only ignore not found error should be ok here

Comment (KanShiori) [reply pkg/controller/tidbcluster/pod_control.go:182]: > then only ignore not found error should be ok here

Done

**Review by july2993 — APPROVED** [review]

File: pkg/controller/tidbcluster/pod_control.go [hunk 2]
```diff
@@ -179,6 +179,16 @@ func (c *PodController) sync(key string) (reconcile.Result, error) {
...
+	if err != nil {
+		if errors.IsNotFound(err) {
+			klog.V(4).Infof("tc is not found, so skip sync tc %q", ns+"/"+tcName)
```
Comment (DanielZhangQD) [inline pkg/controller/tidbcluster/pod_control.go:185]:
```suggestion
			klog.V(4).Infof("TidbCluster %q is not found, skip sync the Pod %s", ns+"/"+tcName, name)
```

File: pkg/controller/tidbcluster/pod_control.go [hunk 3]
```diff
@@ -179,6 +179,16 @@ func (c *PodController) sync(key string) (reconcile.Result, error) {
...
+			return reconcile.Result{}, nil
+		}
+		return reconcile.Result{}, err
```
Comment (DanielZhangQD) [inline pkg/controller/tidbcluster/pod_control.go:188]:
```suggestion
		return reconcile.Result{}, perrors.Annotatef(err, "failed to get TidbCluster %q", ns+"/"+tcName)
```

**Review by DanielZhangQD — APPROVED** [review]
LGTM
