### PR TITLE
fix backup failure on tidb cluster has massive tikv nodes (40+)

### LINKED ISSUE #4781: Operator could not start the volume-snapshot backup
## Bug Report

**What version of Kubernetes are you using?**
1.22
**What version of TiDB Operator are you using?**
1.4.0-beta.2

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
gp3

**What's the status of the TiDB cluster pods?**
ready

**What did you do?**
1. scale tidb cluster to 40+ tikv
2. launch a volume-snapshot backup

**What did you expect to see?**
a backup job can create and run as expected

**What did you see instead?**
the job can not run and fails immediately and shows the error below:
exec /entrypoint.sh: argument list too long

### PR DESCRIPTION
**Pull request by fengou1**
### What problem does this PR solve?
Closes #4781

### What is changed and how does it work?
using the remote storage to pass info between backup manager and controller

### Code changes

- [ ] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [x] Manual test 
 50+ EKS node with tidb cluster has 50 tikv nodes, backup works and completed

AeNHSlVS1e

restore
LVKf2V3nWh

- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

File: images/tidb-operator/Dockerfile [hunk 1]
```diff
@@ -1,8 +1,15 @@
...
 
 ARG TARGETARCH
+ARG RCLONE_VERSION=v1.51.0
 RUN apk add tzdata bind-tools --no-cache
 ADD bin/${TARGETARCH}/tidb-scheduler /usr/local/bin/tidb-scheduler
 ADD bin/${TARGETARCH}/tidb-discovery /usr/local/bin/tidb-discovery
 ADD bin/${TARGETARCH}/tidb-controller-manager /usr/local/bin/tidb-controller-manager
 ADD bin/${TARGETARCH}/tidb-admission-webhook /usr/local/bin/tidb-admission-webhook
+
+RUN wget -nv https://github.com/ncw/rclone/releases/download/${RCLONE_VERSION}/rclone-${RCLONE_VERSION}-linux-${TARGETARCH}.zip \
```
Comment (gozssky) [inline images/tidb-operator/Dockerfile:11]: We can use aws-go-sdk to avoid adding a new binary to tidb-operator's image. There is a simple example in https://github.com/aws/aws-sdk-go#complete-sdk-example.

Comment (fengou1) [reply images/tidb-operator/Dockerfile:11]: there are 3reasons here to use rclone:
1. general handling for remote storage, aws, gcp, ceph, aruze etc. share the same interface rclone copy ....
2. currently, tide-backup-manager uses the rclone, it may be easy to maintain
3. we do not need the complex requirement, only need copy/upload/download. rclone may better choice.

Comment (fengou1) [reply images/tidb-operator/Dockerfile]: fixed in https://github.com/pingcap/tidb-operator/pull/4784/commits/75fa349f322cb6c9de5b3a7d7ef7655b35ff4d3f

File: images/tidb-operator/Dockerfile [hunk 2]
```diff
@@ -1,6 +1,7 @@
 FROM alpine:3.14
 
 ARG TARGETARCH
+ARG RCLONE_VERSION=v1.51.0
```
Comment (WangLe1321) [inline images/tidb-operator/Dockerfile:4]: can we remove this line?

File: pkg/backup/util/util.go [hunk 3]
```diff
@@ -705,3 +695,92 @@ func isLogBackSupport(tikvImage string) bool {
...
+	go func() {
+		sig := <-sc
+		klog.Errorf("got signal %s to exit, %s will be canceled", sig, op)
+		cancel() // NOTE: the `Message` in `Status.Conditions` will contain `context canceled`.
+	}()
+	return ctx, cancel
+}
+
+// GetStorageRestorePath generate the path of a specific storage from Restore
+func GetStorageRestorePath(restore *v1alpha1.Restore) (string, error) {
```
Comment (WangLe1321) [inline pkg/backup/util/util.go:718]: What is the difference of `GetStorageRestorePath` and `GetStorageBackupPath`? I think we can merge them to one function with parameter `StorageProvider`

File: pkg/backup/util/remote.go [hunk 4]
```diff
@@ -315,10 +325,45 @@ func BatchDeleteObjectsConcurrently(ctx context.Context, bucket *blob.Bucket, ob
 	return result
 }
 
+func GetStorageCredential(ns string, provider v1alpha1.StorageProvider, secretLister corelisterv1.SecretLister) *storageCredential {
```
Comment (WangLe1321) [inline pkg/backup/util/remote.go:328]: As it is a public method, I think returning with error or returning an empty object `&storageCredential{}` rather than returning `nil` maybe better. Or it is easy to cause caller encountering nil pointer error.

File: pkg/backup/backup/backup_manager.go [hunk 5]
```diff
@@ -694,10 +693,10 @@ func (bm *backupManager) saveClusterMetaToExternalStorage(b *v1alpha1.Backup, cs
 	return "", nil
 }
 
-func (bm *backupManager) tryBackupIfCanSnapshot(b *v1alpha1.Backup, tc *v1alpha1.TidbCluster) (string, error) {
+func (bm *backupManager) volSnapshotBackup(b *v1alpha1.Backup, tc *v1alpha1.TidbCluster) (string, error) {
 	if s, reason, err := snapshotter.NewSnapshotterForBackup(b.Spec.Mode, bm.deps); err != nil {
 		return reason, err
-	} else if s != nil {
+	} else if s != (&snapshotter.NoneSnapshotter{}) {
```
Comment (WangLe1321) [inline pkg/backup/backup/backup_manager.go:699]:
```suggestion
	} else if _, ok := s.(*snapshotter.NoneSnapshotter); !ok {
```

I think we can use this judgement, or keep `if s != nil`. `s != (&snapshotter.NoneSnapshotter{})` is a wrong method, maybe it compares their address, and it always gets `false`, even if `s := &snapshotter.NoneSnapshotter{}`. In go, we can't compare two objects directly, use `reflect.DeepEqual()` is a choice.

Comment (fengou1) [reply pkg/backup/backup/backup_manager.go]: fix in https://github.com/pingcap/tidb-operator/pull/4784/commits/286dee8f3243b0f3a3f6d3b5f1f927d09a601993

**Review by WangLe1321 — APPROVED** [review]
LGTM

File: pkg/backup/constants/constants.go [hunk 6]
```diff
@@ -93,4 +93,15 @@ const (
...
+	LocalTmp           = "/tmp"
+	ClusterBackupMeta  = "clustermeta"
+	ClusterRestoreMeta = "restoremeta"
+	// RcloneConfigFile represents the path to the file that contains rclone
+	// configs. This path should be the same as defined in docker entrypoint
+	// script from backup-manager/entrypoint.sh. /tmp/rclone.conf
+	RcloneConfigFile = "/tmp/rclone.conf"
+
+	// RcloneConfigArg represents the config argument to rclone cmd
+	RcloneConfigArg = "--config=" + RcloneConfigFile
```
Comment (gozssky) [inline pkg/backup/constants/constants.go:106]:
```suggestion
```

Comment (gozssky) [reply pkg/backup/constants/constants.go:106]: Unused?

File: pkg/backup/restore/restore_manager.go [hunk 7]
```diff
@@ -195,6 +196,44 @@ func (rm *restoreManager) syncRestoreJob(restore *v1alpha1.Restore) error {
...
+		return nil, "NewStorageBackendFailed", err
+	}
+
+	// if file doesn't exist, br create volume has problem
+	exist, err := externalStorage.Exists(ctx, constants.ClusterRestoreMeta)
+	if err != nil {
+		return nil, "FileExistedInExternalStorageFailed", err
+	}
+	if !exist {
+		return nil, "FileExistedInExternalStorage", fmt.Errorf("%s does not exist", constants.ClusterRestoreMeta)
```
Comment (gozssky) [inline pkg/backup/restore/restore_manager.go:220]: `FileExistedInExternalStorage` -> `FileNotExists` ?

File: pkg/backup/restore/restore_manager_test.go [hunk 8]
```diff
@@ -373,17 +421,25 @@ func TestBRRestoreByEBS(t *testing.T) {
...
 		t.Run(tt.name, func(t *testing.T) {
+
 			helper.CreateTC(tt.restore.Spec.BR.ClusterNamespace, tt.restore.Spec.BR.Cluster)
 			helper.CreateRestore(tt.restore)
-			tt.restore.Annotations = map[string]string{
-				label.AnnBackupCloudSnapKey: testutils.ConstructRestoreMetaStr(),
-			}
+			// tt.restore.Annotations = map[string]string{
+			// 	label.AnnBackupCloudSnapKey: testutils.ConstructRestoreMetaStr(),
+			// }
```
Comment (gozssky) [inline pkg/backup/restore/restore_manager_test.go:435]:
```suggestion
```

File: pkg/backup/backup/backup_manager.go [hunk 9]
```diff
@@ -665,11 +659,50 @@ func (bm *backupManager) makeBRBackupJob(backup *v1alpha1.Backup) (*batchv1.Job,
...
 
-func (bm *backupManager) tryBackupIfCanSnapshot(b *v1alpha1.Backup, tc *v1alpha1.TidbCluster) (string, error) {
+// save cluster meta to external storage since k8s size limitation on annotation/configMap
+func (bm *backupManager) saveClusterMetaToExternalStorage(b *v1alpha1.Backup, csb *snapshotter.CloudSnapBackup) (string, error) {
+
+	data, err := json.Marshal(csb)
+	if err != nil {
+		return "ParseCloudSnapshotBackupFailed", err
+	}
+	ctx, cancel := backuputil.GetContextForTerminationSignals(b.ClusterName)
```
Comment (gozssky) [inline pkg/backup/backup/backup_manager.go:669]: Why need to listen to the termination signal?

**Review by gozssky — COMMENTED** [review]
Rest LGTM.

File: pkg/backup/util/remote.go [hunk 10]
```diff
@@ -315,10 +324,45 @@ func BatchDeleteObjectsConcurrently(ctx context.Context, bucket *blob.Bucket, ob
...
+	var secret *corev1.Secret
+	storageType := GetStorageType(provider)
+
+	switch storageType {
+	case v1alpha1.BackupStorageTypeS3:
+		s3SecretName := provider.S3.SecretName
+		if s3SecretName != "" {
+			secret, err = secretLister.Secrets(ns).Get(s3SecretName)
+			if err != nil {
+				return &StorageCredential{}
```
Comment (WizardXiao) [inline pkg/backup/util/remote.go:338]: maybe can write some log or return err

File: cmd/backup-manager/app/util/util.go [hunk 11]
```diff
@@ -351,7 +351,7 @@ func GetBRArchiveSize(meta *kvbackup.BackupMeta) uint64 {
 
 // GetBRMetaData get backup metadata from cloud storage
 func GetBRMetaData(ctx context.Context, provider v1alpha1.StorageProvider) (*kvbackup.BackupMeta, error) {
-	s, err := NewStorageBackend(provider)
+	s, err := util.NewStorageBackend(provider, &util.StorageCredential{})
```
Comment (WizardXiao) [inline cmd/backup-manager/app/util/util.go:354]: just a small suggestion, here will use `util.StorageCredential{}` and will be set by `awsConfig.WithCredentials(cred.awsCred)`, and will set nil to aws api, maybe we can just set nil and don't set to aws api?

Comment (fengou1) [reply cmd/backup-manager/app/util/util.go:354]: My first version is set nil instead of &util.StorageCredential{}, it looks &util.StorageCredential{} more suitable.

Comment (WizardXiao) [reply cmd/backup-manager/app/util/util.go:354]: ok

**Review by WizardXiao — APPROVED** [review]
LGTM

File: pkg/backup/backup/backup_manager.go (hunk 9 above)
Comment (fengou1) [reply pkg/backup/backup/backup_manager.go]: fix in https://github.com/pingcap/tidb-operator/pull/4784/commits/d37ccf3973fcd2463ece589df5ffa2f9a46b0585

**Review by gozssky — APPROVED** [review]
