### PR TITLE
Fixed potential nil pointer issues

### LINKED ISSUE #4051: panic issues triggered by no TiDB
## Bug Report

**What version of Kubernetes are you using?**

v1.15.0

**What version of TiDB Operator are you using?**

v1.1.9
**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

NAME                         PROVISIONER                    AGE
nvme-disks                   kubernetes.io/no-provisioner   182d
shared-nvme-disks            kubernetes.io/no-provisioner   182d
shared-sas-disks (default)   kubernetes.io/no-provisioner   182d
**What's the status of the TiDB cluster pods?**

no started
**What did you do?**

**What did you expect to see?**
works well.
**What did you see instead?**
```
E0630 05:33:14.247218       1 tidb_monitor_controller.go:92] TidbMonitor: csn/monitor-2, sync failed, err: get tm[csn/monitor-2]'s target tc[csn/tiny-2] failed, err: tidbcluster.pingcap.com "tiny-2" not found
E0630 05:33:14.248293       1 tidb_monitor_controller.go:92] TidbMonitor: liubo02/basic, sync failed, err: get tm[liubo02/basic]'s target tc[liubo02/basic] failed, err: tidbcluster.pingcap.com "basic" not found
E0630 05:33:14.249267       1 tidb_monitor_controller.go:92] TidbMonitor: nolouch/monitor, sync failed, err: get tm[nolouch/monitor]'s target tc[nolouch/test] failed, err: tidbcluster.pingcap.com "test" not found
E0630 05:33:14.502243       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 733 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1bb0420, 0x2d494e0)
	k8s.io/apimachinery@v0.0.0/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	k8s.io/apimachinery@v0.0.0/pkg/util/runtime/runtime.go:48 +0x89
panic(0x1bb0420, 0x2d494e0)
	runtime/panic.go:969 +0x1b9
github.com/pingcap/tidb-operator/pkg/apis/pingcap/v1alpha1.(*TidbCluster).IsTiDBBinlogEnabled(...)
	github.com/pingcap/tidb-operator/pkg/apis/pingcap/v1alpha1/tidbcluster.go:608
github.com/pingcap/tidb-operator/pkg/monitor/monitor.getMonitorInitContainer(0xc000cca400, 0xc0002ab830, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/pingcap/tidb-operator/pkg/monitor/monitor/util.go:286 +0x1d8
github.com/pingcap/tidb-operator/pkg/monitor/monitor.getMonitorStatefulSet(0xc0027c3080, 0xc001ca2c80, 0xc000300500, 0xc000cca400, 0xc0002ab830, 0x0, 0x0, 0xc001db16c8, 0x8fd7d3)
	github.com/pingcap/tidb-operator/pkg/monitor/monitor/util.go:975 +0x7b
github.com/pingcap/tidb-operator/pkg/monitor/monitor.(*MonitorManager).syncTidbMonitorStatefulset(0xc000492f30, 0xc0002ab830, 0x0, 0xc000cca400, 0x0, 0x0)
	github.com/pingcap/tidb-operator/pkg/monitor/monitor/monitor_manager.go:200 +0x5a7
github.com/pingcap/tidb-operator/pkg/monitor/monitor.(*MonitorManager).SyncMonitor(0xc000492f30, 0xc000cca400, 0xc000e1b2f0, 0xc0005a2c60)
	github.com/pingcap/tidb-operator/pkg/monitor/monitor/monitor_manager.go:130 +0x685
o:69 +0x192
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x160 pc=0x19c6318]

goroutine 733 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	k8s.io/apimachinery@v0.0.0/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x1bb0420, 0x2d494e0)
	runtime/panic.go:969 +0x1b9
github.com/pingcap/tidb-operator/pkg/apis/pingcap/v1alpha1.(*TidbCluster).IsTiDBBinlogEnabled(...)
	github.com/pingcap/tidb-operator/pkg/apis/pingcap/v1alpha1/tidbcluster.go:608
github.com/pingcap/tidb-operator/pkg/monitor/monitor.getMonitorInitContainer(0xc000cca400, 0xc0002ab830, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/pingcap/tidb-operator/pkg/monitor/monitor/util.go:286 +0x1d8
github.com/pingcap/tidb-operator/pkg/monitor/monitor.getMonitorStatefulSet(0xc0027c3080, 0xc001ca2c80, 0xc000300500, 0xc000cca400, 0xc0002ab830, 0x0, 0x0, 0xc001db16c8, 0x8fd7d3)
	github.com/pingcap/tidb-operator/pkg/monitor/monitor/util.go:975 +0x7b
github.com/pingcap/tidb-operator/pkg/monitor/monitor.(*MonitorManager).syncTidbMonitorStatefulset(0xc000492f30, 0xc0002ab830, 0x0, 0xc000cca400, 0x0, 0x0)
	github.com/pingcap/tidb-operator/pkg/monitor/monitor/monitor_manager.go:200 +0x5a7
github.com/pingcap/tidb-operator/pkg/monitor/monitor.(*MonitorManager).SyncMonitor(0xc000492f30, 0xc000cca400, 0xc000e1b2f0, 0xc0005a2c60)
	github.com/pingcap/tidb-operator/pkg/monitor/monitor/monitor_manager.go:130 +0x685
github.com/pingcap/tidb-operator/pkg/controller/tidbmonitor.(*defaultTidbMonitorControl).reconcileTidbMonitor(0xc00000d400, 0xc000cca400, 0x2135620, 0xc000e8b080)
	github.com/pingcap/tidb-operator/pkg/controller/tidbmonitor/tidb_monitor_control.go:60 +0xa5
github.com/pingcap/tidb-operator/pkg/controller/tidbmonitor.(*defaultTidbMonitorControl).ReconcileTidbMonitor(0xc00000d400, 0xc0007c3310, 0x0, 0x0)
	github.com/pingcap/tidb-operator/pkg/controller/tidbmonitor/tidb_monitor_control.go:50 +0x45
github.com/pingcap/tidb-operator/pkg/controller/tidbmonitor.(*Controller).sync(0xc000492ff0, 0xc000840240, 0x12, 0x0, 0x0)
	github.com/pingcap/tidb-operator/pkg/controller/tidbmonitor/tidb_monitor_controller.go:120 +0x239
github.com/pingcap/tidb-operator/pkg/controller/tidbmonitor.(*Controller).processNextWorkItem(0xc000492ff0, 0x0)
	github.com/pingcap/tidb-operator/pkg/controller/tidbmonitor/tidb_monitor_controller.go:88 +0xed
github.com/pingcap/tidb-operator/pkg/controller/tidbmonitor.(*Controller).worker(0xc000492ff0)
	github.com/pingcap/tidb-operator/pkg/controller/tidbmonitor/tidb_monitor_controller.go:76 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000a187b0)
	k8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000a187b0, 0x3b9aca00, 0x0, 0x1, 0xc00024a060)
	k8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:153 +0x105
k8s.io/apimachinery/pkg/util/wait.Until(0xc000a187b0, 0x3b9aca00, 0xc00024a060)
	k8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:88 +0x4d
created by github.com/pingcap/tidb-operator/pkg/controller/tidbmonitor.(*Controller).Run
	github.com/pingcap/tidb-operator/pkg/controller/tidbmonitor/tidb_monitor_controller.go:69 +0x192
```

### PR DESCRIPTION
**Pull request by KanShiori**
### What problem does this PR solve?

Fix #4051
Fixed potential nil pointer issues.

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [x] Unit test 
- [ ] E2E test 
- [x] Manual test 

* Test upgrade
  1. Upgrade `TiDB-Opertaor` and check the cluster is normal.
* Test depolyment
  * Deploy new cluster and monitor, then check function.
  * Deploy  new cluster without `PD` ,  then check pods and watch logs of `TiDB-Operator`.
     ```shell
     NAME                                READY   STATUS    RESTARTS   AGE
     my-tidb-cluster-dev-pump-0          0/1     Running   1          114s
     my-tidb-cluster-dev-ticdc-0         1/1     Running   0          114s
     my-tidb-cluster-dev-ticdc-1         1/1     Running   0          114s
     my-tidb-cluster-dev-ticdc-2         1/1     Running   0          114s
     my-tidb-cluster-dev-tiflash-0       4/4     Running   0          114s
     my-tidb-cluster-dev-tikv-0          3/3     Running   0          114s
     my-tidb-cluster-dev-tikv-1          3/3     Running   0          114s
     my-tidb-cluster-dev-tikv-2          3/3     Running   0          114s
     my-tidb-cluster-monitor-monitor-0   4/4     Running   0          26m
     ```
  * Deploy  new cluster without `TiDB`,  then check pods and watch logs of `TiDB-Operator`.
    ```shell
    NAME                                             READY   STATUS    RESTARTS   AGE
    my-tidb-cluster-dev-discovery-85b8698c6c-tfgcs   1/1     Running   0          3m2s
    my-tidb-cluster-dev-pd-0                         1/1     Running   0          3m1s
    my-tidb-cluster-dev-pd-1                         1/1     Running   0          3m1s
    my-tidb-cluster-dev-pd-2                         1/1     Running   0          3m1s
    my-tidb-cluster-dev-pump-0                       1/1     Running   0          2m18s
    my-tidb-cluster-dev-pump-1                       1/1     Running   0          2m16s
    my-tidb-cluster-dev-pump-2                       1/1     Running   0          2m14s
    my-tidb-cluster-dev-ticdc-0                      1/1     Running   0          2m15s
    my-tidb-cluster-dev-ticdc-1                      1/1     Running   0          2m15s
    my-tidb-cluster-dev-ticdc-2                      1/1     Running   0          2m15s
    my-tidb-cluster-dev-tiflash-0                    4/4     Running   0          2m15s
    my-tidb-cluster-dev-tikv-0                       3/3     Running   0          2m18s
    my-tidb-cluster-dev-tikv-1                       3/3     Running   0          2m18s
    my-tidb-cluster-dev-tikv-2                       3/3     Running   0          2m18s
    my-tidb-cluster-monitor-monitor-0                4/4     Running   0          163m
    ```
  * Deploy  new cluster without `TiKV` ,  then check pods and watch logs of `TiDB-Operator`.
     ```shell
     kubectl get pods
    NAME                                             READY   STATUS    RESTARTS   AGE
    my-tidb-cluster-dev-discovery-85b8698c6c-bjf6m   1/1     Running   0          4m27s
    my-tidb-cluster-dev-pd-0                         1/1     Running   0          4m26s
    my-tidb-cluster-dev-pd-1                         1/1     Running   0          4m26s
    my-tidb-cluster-dev-pd-2                         1/1     Running   0          4m26s
    my-tidb-cluster-dev-pump-0                       1/1     Running   0          3m41s
    my-tidb-cluster-dev-pump-1                       1/1     Running   0          3m39s
    my-tidb-cluster-dev-pump-2                       1/1     Running   0          3m36s
    my-tidb-cluster-dev-ticdc-0                      1/1     Running   0          3m40s
    my-tidb-cluster-dev-ticdc-1                      1/1     Running   0          3m40s
    my-tidb-cluster-dev-ticdc-2                      1/1     Running   0          3m40s
    my-tidb-cluster-dev-tidb-0                       1/2     Running   1          3m37s
    my-tidb-cluster-dev-tidb-1                       1/2     Running   1          3m37s
    my-tidb-cluster-dev-tidb-2                       1/2     Running   1          3m37s
    my-tidb-cluster-dev-tiflash-0                    4/4     Running   0          3m40s
    my-tidb-cluster-monitor-monitor-0                4/4     Running   0          20m
    ```
  * Deploy  new cluster without `Pump` ,  then check pods and watch logs of `TiDB-Operator`.
  * Deploy  new cluster without `TiFlash` ,  then check pods and watch logs of `TiDB-Operator`.
  * Deploy  new cluster without `TiCDC` ,  then check pods and watch logs of `TiDB-Operator`.
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note
Fix the issue that TiDB Operator may panic when heterogeneous clusters are deployed
```

### CODE REVIEW

File: pkg/apis/pingcap/v1alpha1/tidbcluster.go [hunk 1]
```diff
@@ -95,7 +116,14 @@ func (tc *TidbCluster) TiKVImage() string {
 	return image
 }
 
+// TiKVVersion return the image used by TiKV.
```
Comment (DanielZhangQD) [inline pkg/apis/pingcap/v1alpha1/tidbcluster.go:119]:
```suggestion
// TiKVVersion return the image version used by TiKV.
```

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Review by csuzhangxc — APPROVED** [review]
LGTM
