### PR TITLE
ebs: adjust volume tagging

### LINKED ISSUE #5506: File based warmup checkpoint is unavailable if the root directory isn't a PV
## Bug Report

**What version of Kubernetes are you using?**
N/A

**What version of TiDB Operator are you using?**
N/A

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
N/A

**What's the status of the TiDB cluster pods?**
N/A

**What did you do?**
Run EBS Restore, with hybrid warmup method, delete the warmup pod.

**What did you expect to see?**
The new warmup pod should be able to continue from the last checkpoint.

**What did you see instead?**
It runs from the `time.Now()`. (i.e. will warmup all files.)

### PR DESCRIPTION
**Pull request by BornChanger**
### What problem does this PR solve?

Closes #5506 

### What is changed and how does it work?

Add pvc name as tag of restored volume

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [x] Manual test 
image

- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Review by WangLe1321 — APPROVED** [review]

File: pkg/backup/snapshotter/snapshotter_aws.go [hunk 1]
```diff
@@ -105,8 +104,10 @@ func (s *AWSSnapshotter) AddVolumeTags(pvs []*corev1.PersistentVolume) error {
 	for _, pv := range pvs {
 		tags := make(map[string]string)
 		tags[PVCTagKey] = pv.GetName()
-		tags[PodTagKey] = pv.GetAnnotations()[label.AnnPodNameKey]
-		tags[PodNSTagKey] = pv.GetLabels()[label.NamespaceLabelKey]
+		if pv.Spec.ClaimRef != nil {
+			tags[PvcNameTagKey] = pv.Spec.ClaimRef.Name
+			tags[PvcNSTagKey] = pv.Spec.ClaimRef.Namespace
```
Comment (nkg-) [inline pkg/backup/snapshotter/snapshotter_aws.go:109]: The code seems correct But the screenshot in the PR does NOT show the tag "kubernetes.io/created-for/pvc/namespace", but rather shows "snapshot/kubernetes.io/created-for/pvc/namespace".
