### PR TITLE
br: clean volumes when restore volume failed

### LINKED ISSUE #5638: Volume leaked if volume restore failed in restore volume step
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

v1.5

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

execute a volume restore, but the restore failed due to restore volume failed.

**What did you expect to see?**

some volumes are restored, these volumes can be cleaned by tidb-operator automatically

**What did you see instead?**

the restored volumes are still reserved in aws console

### PR DESCRIPTION
**Pull request by WangLe1321**
### What problem does this PR solve?

Add cleaning volumes function when restore volume failed. Then we can avoid volume leak

Closes #5638

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [x] Manual test 
- [ ] No code 

manual test steps:

1. create a cluster
2. create a volume backup
3. create a restore cluster
4. create a volume restore using the volume backup in step 2. in this step, restore volume is successful and the tikv pods are started
5. edit the restore CR, modify its status from `VolumeComplete` to `Failed` to mock restore volume failed scenario
6. edit the tc CR, remove the annotation `tidb.pingcap.com/tikv-volumes-ready` to block tikv creation, then delete the tikv statefulset to detach the EBS volumes
7. wait for the volumes detached and deleted by tidb-operator

image

image

image

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Review by BornChanger — APPROVED** [review]

**Review by csuzhangxc — APPROVED** [review]

File: pkg/apis/pingcap/v1alpha1/restore.go [hunk 1]
```diff
@@ -130,6 +130,19 @@ func IsRestoreVolumeComplete(restore *Restore) bool {
 	return condition != nil && condition.Status == corev1.ConditionTrue
 }
 
+// IsRestoreVolumeFailed returns true if a Restore for volume is Failed
+func IsRestoreVolumeFailed(restore *Restore) bool {
```
Comment (nkg-) [inline pkg/apis/pingcap/v1alpha1/restore.go:134]: Trying to understand this what exactly does IsRestoreVolumeFailed entail.  

We should only delete volumes, if restore fails in the first step (ie RestoreVolume which creates the volumes), and before creating PV/PVCs which attach volumes to ec2 nodes. Its the volumes which are never attached to an ec2 node (via PVCs) which cause a leak. After PVCs are created, they are tracked and deleted by csi driver. 

Also If they restore fails during warmup, or restore_data, its actually useful to investigate the tikvs on what happened. If the volumes are deleted, then it would be hard to investigate.

File: pkg/backup/util/aws_ebs.go [hunk 2]
```diff
@@ -204,6 +205,68 @@ func (e *EC2Session) DeleteSnapshots(snapIDMap map[string]string, deleteRatio fl
 	return nil
 }
 
+func (e *EC2Session) DeleteVolumes(volumeIDs []string) error {
```
Comment (nkg-) [inline pkg/backup/util/aws_ebs.go:208]: We should only delete volumes, which are unattached. How is the validated here.

**Review by nkg- — COMMENTED** [review]
THanks for working on it. Left a couple of comments.

File: pkg/backup/util/aws_ebs.go (hunk 2 above)
Comment (WangLe1321) [reply pkg/backup/util/aws_ebs.go:208]: If the volume is attached, the delete request will fail. It means, we can't delete an attached volume. In my test, if the tikv pod is running, the volume can't be deleted. This is the reason why I deleted the tikv statefulset in my test steps.

File: pkg/apis/pingcap/v1alpha1/restore.go (hunk 1 above)
Comment (WangLe1321) [reply pkg/apis/pingcap/v1alpha1/restore.go:134]: We create pv/pvc and warm up volumes and restore data **only** if the restore CR has the status RestoreVolumeComplete. And if restore volume failed, the status of restore CR is Failed. So this condition can ensure the restore is failed at restore volume step.

Comment (nkg-) [reply pkg/apis/pingcap/v1alpha1/restore.go:134]: Got it. So `!IsRestoreVolumeComplete(restore)` is the condition which ensure restorevolume step has failed.

File: pkg/backup/util/aws_ebs.go (hunk 2 above)
Comment (nkg-) [reply pkg/backup/util/aws_ebs.go:208]: Got it. Basically we rely in aws api contract to prevent attached volumes from getting deleted. `Deletes the specified EBS volume. The volume must be in the available state (not attached to an instance).`

https://docs.aws.amazon.com/cli/latest/reference/ec2/delete-volume.html

**Review by nkg- — COMMENTED** [review]
Thanks for the responses.
