### PR TITLE
use the real desired replicas in HA predicate (#3171)

### LINKED ISSUE #1594: the pod of pd or tikv will be pending when there are three nodes in k8s and replicas which is set by tc are above 3
## Bug Report

**What version of Kubernetes are you using?**
v1.16.3

**What version of TiDB Operator are you using?**
v1.0.5

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
local-storage

**What's the status of the TiDB cluster pods?**
tidbcluster-wuhanwuli-tikv-0                       0/1     Pending     0          11d
tidbcluster-wuhanwuli-tikv-1                       1/1     Running     17         12d
tidbcluster-wuhanwuli-tikv-2                       1/1     Running     18         12d
tidbcluster-wuhanwuli-tikv-3                       0/1     Pending     0          12d

**What did you do?**
there are 3 nodes in k8s. make a node down, then use a new server to recover the node, make new pv in the new node.

**What did you expect to see?**
all the tikv's pods can become running

**What did you see instead?**
some of the tikv's pods are pending, unless add new nodes and new pv

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #3171 to release-1.1

---

### What problem does this PR solve? 
fix #1594 
### Check List 

Tests 

 - Unit test
 - E2E test
 - Stability test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has Go code change
 - Has CI related scripts change
 - Has Terraform scripts change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Review by DanielZhangQD — APPROVED** [review]
LGTM

File: pkg/scheduler/predicates/ha_test.go [hunk 1]
```diff
@@ -1164,6 +1177,26 @@ func tcGetTwoReplicasFn(ns string, tcName string) (*v1alpha1.TidbCluster, error)
...
 
+func tcGetThreeAndOneFailoverReplicaFn(ns string, tcName string) (*v1alpha1.TidbCluster, error) {
+	return &v1alpha1.TidbCluster{
+		TypeMeta: metav1.TypeMeta{Kind: "TidbCluster", APIVersion: "v1alpha1"},
+		ObjectMeta: metav1.ObjectMeta{
+			Name:      tcName,
+			Namespace: ns,
+		},
+		Spec: v1alpha1.TidbClusterSpec{
+			TiKV: &v1alpha1.TiKVSpec{Replicas: 3},
```
Comment (cofyc) [inline pkg/scheduler/predicates/ha_test.go:1188]:
```suggestion
			TiKV: v1alpha1.TiKVSpec{Replicas: 3},
```

**Review by cofyc — APPROVED** [review]
