### PR TITLE
e2e: use helm 2.9.1

### LINKED ISSUE #1267: e2e: helm fails with "unable to retrieve the complete list of server APIs" error
## Bug Report

https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/build_tidb_operator_master_kind/runs/179/nodes/66/steps/98/log/?start=0

```
failed to deploy tidbcluster: tidb-cluster-5425/cluster4, exit status 1, Error: Could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: example.pingcap.com/v1alpha1: the server could not find the requested resource, example.pingcap.com/v1beta1: the server could not find the requested resource
```

This is because of this helm issue: https://github.com/helm/helm/issues/6361 (fixed on master via https://github.com/helm/helm/pull/6908).

Both helm 2.15/2.16 series have this issue and are not fixed yet.

We can use helm version 2.14.

Alternatively, we can retry on helm operation.

### PR DESCRIPTION
**Pull request by cofyc**
### What problem does this PR solve? 

fixes #1267 

### What is changed and how does it work?

workaround a helm issue

### Check List 

Tests 

 - Unit test
 - E2E test

### CODE REVIEW

File: tests/images/e2e/Dockerfile [hunk 1]
```diff
@@ -1,7 +1,7 @@
 FROM alpine:3.10
 
 ENV KUBECTL_VERSION=v1.12.2
-ENV HELM_VERSION=v2.9.1
+ENV HELM_VERSION=v2.14.3
```
Comment (cofyc) [inline tests/images/e2e/Dockerfile]: same as helm server version

File: hack/e2e.sh [hunk 2]
```diff
@@ -259,13 +277,24 @@ for ((i = 1; i <= 32; i++)) {
...
+    $KUBECTL_BIN --context $KUBECONTEXT apply -f ${ROOT}/manifests/tiller-rbac.yaml
+    if hack::version_ge $KUBE_VERSION "v1.16.0"; then
+        # workaround for https://github.com/helm/helm/issues/6374
+        # TODO remove this when we can upgrade to helm 2.15+, see https://github.com/helm/helm/pull/6462
+        $HELM_BIN init --service-account tiller --output yaml \
+            | sed 's@apiVersion: extensions/v1beta1@apiVersion: apps/v1@' \
+            | sed 's@  replicas: 1@  replicas: 1\n  selector: {"matchLabels": {"app": "helm", "name": "tiller"}}@' \
+            | $KUBECTL_BIN --context $KUBECONTEXT apply -f -
+        echo "info: wait for tiller to be ready"
+		e2e::__wait_for_deploy kube-system tiller-deploy
```
Comment (cofyc) [inline hack/e2e.sh]: we need this hack because helm (<= 2.14) cannot be installed in 1.16.0+ via  `helm init` command

File: hack/e2e.sh [hunk 3]
```diff
@@ -221,7 +221,7 @@ EOF
 function e2e::__wait_for_ds() {
     local ns="$1"
     local name="$2"
-    local retries="${3:-120}"
+    local retries="${3:-300}"
```
Comment (cofyc) [inline hack/e2e.sh]: be stable when network is slow

File: tests/actions.go [hunk 4]
```diff
@@ -2527,6 +2527,7 @@ func (oa *operatorActions) disableScheduledBackup(info *TidbClusterConfig) error
 		return err
 	}
 
+	glog.Infof("scheduled-backup disable [%s]", cmd)
```
Comment (cofyc) [inline tests/actions.go]: print cmd for debugging

File: tests/actions.go [hunk 5]
```diff
@@ -2506,7 +2506,7 @@ func (oa *operatorActions) DeployScheduledBackup(info *TidbClusterConfig) error
 		return err
 	}
 
-	glog.Infof("scheduled-backup delploy [%s]", cmd)
+	glog.Infof("scheduled-backup deploy [%s]", cmd)
```
Comment (cofyc) [inline tests/actions.go]: fix typo
