### PR TITLE
don't failover if TiDB pod is not scheduled and perform recovery no matter what state failover pods are in

### LINKED ISSUE #2155: Failover will be triggered after the TiDB pod is in the Pending state for five minutes
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

`v1.0.6`

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

Create a TiDB Cluster, if a TiDB Pod is Pending, failover will be triggered after five minutes.

**What did you expect to see?**

**What did you see instead?**

### PR DESCRIPTION
**Pull request by cofyc**
### What problem does this PR solve? 
fixes #2155
### Check List 

Tests 

 - Unit test
 - E2E test
 - Stability test
 - Manual test (add detailed scripts or steps below)
 - No code

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-e2e-gke-ci-master-stability/detail/tidb-operator-e2e-gke-ci-master-stability/54/pipeline

Code changes

 - Has Go code change
 - Has CI related scripts change
 - Has Terraform scripts change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Does this PR introduce a user-facing change?:

```release-note
Skip auto-failover when pods are not scheduled and perform recovery operation no matter what state failover pods are in
```

### CODE REVIEW

**Comment by cofyc** [comment]
> Do we need to also support this feature for tikv and pd?

at least, PD is required, see https://github.com/pingcap/tidb-operator/issues/2161.
one failed replica may cause more than one replacements to be created in failover. 

I'm going to fix #2161 first.

File: tests/e2e/tidbcluster/stability.go [hunk 1]
```diff
@@ -129,11 +132,6 @@ var _ = ginkgo.Describe("[tidb-operator][Stability]", func() {
 			framework.ExpectNoError(err, "failed to create clientset")
 		})
 
-		ginkgo.AfterEach(func() {
-			ginkgo.By("Uninstall tidb-operator")
-			oa.CleanOperatorOrDie(ocfg)
-		})
```
Comment (cofyc) [inline tests/e2e/tidbcluster/stability.go:135]: easier to debug in development

File: tests/actions.go [hunk 2]
```diff
@@ -1398,6 +1405,10 @@ func (oa *operatorActions) pdMembersReadyFn(tc *v1alpha1.TidbCluster) (bool, err
 		return false, nil
 	}
 
+	if pdSet.Status.CurrentRevision != pdSet.Status.UpdateRevision {
+		return false, nil
+	}
```
Comment (cofyc) [inline tests/actions.go:1410]: make sure all pods of StatefulSet are up to date
