### PR TITLE
use the latest version object in deletion request

### LINKED ISSUE #2699: Pod cannot be scaled out after scaled in
## Bug Report

**What version of Kubernetes are you using?**

v1.12.8
**What version of TiDB Operator are you using?**

v1.1.0
**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

local-storage
**What's the status of the TiDB cluster pods?**

Running
**What did you do?**

Scale out TiKV from 3 to 6, then from 6 to 3, then from 3 to 6
**What did you expect to see?**
TiKV Pod are scaled in/out successfully
**What did you see instead?**
After the 3rd operation, `then from 3 to 6`, the Pods are scaled out but Pending due to no PVC found.

### PR DESCRIPTION
**Pull request by cofyc**
### What problem does this PR solve? 
fixes #2699 
### Check List 

Tests 

 - Unit test
 - E2E test
 - Stability test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has Go code change
 - Has CI related scripts change
 - Has Terraform scripts change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Does this PR introduce a user-facing change?:

```release-note
Fix an issue that pods may be stuck in pending for a long time in scale-out after a scale-in
```

### CODE REVIEW

File: pkg/controller/tidbcluster/tidb_cluster_control.go [hunk 1]
```diff
@@ -143,8 +143,12 @@ func (tcc *defaultTidbClusterControl) updateTidbCluster(tc *v1alpha1.TidbCluster
 	}
 
 	// cleaning all orphan pods(pd, tikv or tiflash which don't have a related PVC) managed by operator
-	if _, err := tcc.orphanPodsCleaner.Clean(tc); err != nil {
+	if skipReasons, err := tcc.orphanPodsCleaner.Clean(tc); err != nil {
 		return err
+	} else {
+		for podName, reason := range skipReasons {
+			klog.V(10).Infof("pod %s of cluster %s/%s is skipped, reason %q", podName, tc.Namespace, tc.Name, reason)
```
Comment (cofyc) [inline pkg/controller/tidbcluster/tidb_cluster_control.go:150]: high-frequency logs but may be useful in debugging

File: pkg/controller/tidbcluster/tidb_cluster_control.go [hunk 2]
```diff
@@ -231,8 +235,12 @@ func (tcc *defaultTidbClusterControl) updateTidbCluster(tc *v1alpha1.TidbCluster
 	}
 
 	// cleaning the pod scheduling annotation for pd and tikv
-	if _, err := tcc.pvcCleaner.Clean(tc); err != nil {
+	if skipReasons, err := tcc.pvcCleaner.Clean(tc); err != nil {
 		return err
+	} else {
+		for pvcName, reason := range skipReasons {
+			klog.V(10).Infof("pvc %s of cluster %s/%s is skipped, reason %q", pvcName, tc.Namespace, tc.Name, reason)
```
Comment (cofyc) [inline pkg/controller/tidbcluster/tidb_cluster_control.go:242]: high-frequency logs but may be useful in debugging

File: pkg/controller/tidbcluster/tidb_cluster_control.go [hunk 3]
```diff
@@ -143,8 +143,14 @@ func (tcc *defaultTidbClusterControl) updateTidbCluster(tc *v1alpha1.TidbCluster
 	}
 
 	// cleaning all orphan pods(pd, tikv or tiflash which don't have a related PVC) managed by operator
-	if _, err := tcc.orphanPodsCleaner.Clean(tc); err != nil {
+	if skipReasons, err := tcc.orphanPodsCleaner.Clean(tc); err != nil {
 		return err
+	} else {
+		if klog.V(10) {
+			for podName, reason := range skipReasons {
+				klog.Infof("pod %s of cluster %s/%s is skipped, reason %q", podName, tc.Namespace, tc.Name, reason)
```
Comment (cofyc) [inline pkg/controller/tidbcluster/tidb_cluster_control.go:151]: high-frequency logs but may be useful in debugging

File: pkg/controller/tidbcluster/tidb_cluster_control.go [hunk 4]
```diff
@@ -231,8 +237,14 @@ func (tcc *defaultTidbClusterControl) updateTidbCluster(tc *v1alpha1.TidbCluster
 	}
 
 	// cleaning the pod scheduling annotation for pd and tikv
-	if _, err := tcc.pvcCleaner.Clean(tc); err != nil {
+	if skipReasons, err := tcc.pvcCleaner.Clean(tc); err != nil {
 		return err
+	} else {
+		if klog.V(10) {
+			for pvcName, reason := range skipReasons {
+				klog.Infof("pvc %s of cluster %s/%s is skipped, reason %q", pvcName, tc.Namespace, tc.Name, reason)
```
Comment (cofyc) [inline pkg/controller/tidbcluster/tidb_cluster_control.go:245]: high-frequency logs but may be useful in debugging

**Comment by cofyc** [comment]
@DanielZhangQD fixed a lint error
