### PR TITLE
drop retool, replace gometalinter with golangci-lint, and fix spellings

### LINKED ISSUE #1152: CI: Drop retool and gometalinter
`twitchtv/retool` is out of maintenance and `alecthomas/gometalinter` has been deprecated. 

Now that we have upgraded to go `v1.13` in which go module is enabled by default, it is better to drop retool and manage these tools ~in go module~ in scripts instead.

The deprecated tool gometalinter should be dropped too.

### PR DESCRIPTION
**Pull request by cofyc**
### What problem does this PR solve? 
fixes #1152
### Check List 

Tests 

 - Unit test
 - E2E test
 - Stability test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has Go code change
 - Has CI related scripts change
 - Has Terraform scripts change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

File: pkg/apiserver/storage/store.go [hunk 1]
```diff
@@ -293,7 +293,6 @@ func (s *store) GuaranteedUpdate(ctx context.Context,
 				}
 				return err
 			}
-			shouldRefresh = false
```
Comment (cofyc) [inline pkg/apiserver/storage/store.go:296]: reported by `ineffassign`:

```
pkg/apiserver/storage/store.go:296:4: ineffectual assignment to `shouldRefresh` (ineffassign)
			shouldRefresh = false
			^
```

File: hack/verify-spelling.sh [hunk 2]
```diff
@@ -0,0 +1,34 @@
+#!/usr/bin/env bash
```
Comment (cofyc) [inline hack/verify-spelling.sh:1]: we add this to check all files

`golangci-lint` just checks the go source code

File: hack/tools/README.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+This directory contains a stub go module used to track version of development
```
Comment (cofyc) [inline hack/tools/README.md:1]: we compile tools in a separate module, then our project module will not be touched

File: .golangci.yml [hunk 4]
```diff
@@ -0,0 +1,12 @@
+linters:
+  enable:
+    - gofmt
+  disable:
+    # Enable once related errors are fixed or ignored explicitly
```
Comment (cofyc) [inline .golangci.yml:5]: some useful linters can't pass right now, we can enable them in follow up PRs

**Comment by cofyc** [comment]
@DanielZhangQD increased golangci-lint timeout (the default timeout is too small in Github Action CI)
