### PR TITLE
bugfix: get time string from current time instead of pod name

### LINKED ISSUE #1227: scheduled-backup failed to start when clusterName is too long
## Bug Report

Scheduled backup [gets](https://github.com/pingcap/tidb-operator/blob/v1.0.4/charts/tidb-cluster/templates/scripts/_start_scheduled_backup.sh.tpl#L5) `timestamp` from the `POD_NAME`, this will be wrong if the `clusterName` is too long, for example, the `clusterName` is 32 words long, the `timestamp` var will be the word `backup`:

```
$ echo "ssssssssssssssssssssssssssssssss-scheduled-backup-157465068x4n5" | awk -F- '{print $(NF-1)}'
backup
```

### PR DESCRIPTION
**Pull request by weekface**
### What problem does this PR solve? 

fixes #1227 

### Check List 

Tests 

Code changes

 - Has Helm charts change

Side effects

Related changes

 - Need to cherry-pick to the release branch

### Does this PR introduce a user-facing change?:
 
 ```release-note
get time string from current time instead of pod name
 ```

### CODE REVIEW

File: charts/tidb-cluster/templates/scripts/_start_scheduled_backup.sh.tpl [hunk 1]
```diff
@@ -2,9 +2,7 @@ set -euo pipefail
 
 host=$(getent hosts {{ template "cluster.name" . }}-tidb | head | awk '{print $1}')
 
-timestamp=$(echo ${POD_NAME}|awk -F- '{print $(NF-1)}')
-## use UTC time zone to resolve timestamp, avoiding different parsing results due to different default time zones
-backupName=scheduled-backup-`date -u -d @${timestamp}  "+%Y%m%d-%H%M%S"`
+backupName=scheduled-backup-`date "+%Y%m%d-%H%M%S"`
```
Comment (weekface) [inline charts/tidb-cluster/templates/scripts/_start_scheduled_backup.sh.tpl]: Use [`TZ` env](https://github.com/pingcap/tidb-operator/blob/v1.0.4/charts/tidb-cluster/templates/scheduled-backup-cronjob.yaml#L66) timezone information of the pod instead of `UTC`.

Comment (onlymellb) [inline charts/tidb-cluster/templates/scripts/_start_scheduled_backup.sh.tpl]: I recommend continuing to use `UTC` timestamps `date  -u "+%Y%m%d-%H%M%S"`

Comment (weekface) [reply charts/tidb-cluster/templates/scripts/_start_scheduled_backup.sh.tpl]: It should be strange if the user set `TZ` already.

Comment (onlymellb) [reply charts/tidb-cluster/templates/scripts/_start_scheduled_backup.sh.tpl]: 👌

**Comment by tennix** [comment]
Does this impact the restore from the scheduled backup?

**Comment by weekface** [comment]
The generated name is the same as the old way: `"+%Y%m%d-%H%M%S"`, for example: `scheduled-backup-20190822-041004`. So it should not impact restore behavior.
