### PR TITLE
fix backup stage order

### LINKED ISSUE #3904: stage for backup CR looks confusing
## Question

https://github.com/pingcap/tidb-operator/blob/697fd25ee728f900e81969fa4dd82181d81be171/cmd/backup-manager/app/backup/manager.go#L146

https://github.com/pingcap/tidb-operator/blob/697fd25ee728f900e81969fa4dd82181d81be171/cmd/backup-manager/app/backup/manager.go#L170

We set backup(br) job's status from Running -> Prepare -> Completed, which looks very confusing.

https://github.com/pingcap/tidb-operator/blob/697fd25ee728f900e81969fa4dd82181d81be171/cmd/backup-manager/app/export/manager.go#L157

https://github.com/pingcap/tidb-operator/blob/697fd25ee728f900e81969fa4dd82181d81be171/cmd/backup-manager/app/export/manager.go#L341

It looks the same for export(dumpling) job.

### PR DESCRIPTION
**Pull request by liubog2008**
### What problem does this PR solve?

Closes #3904

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [ ] Manual test 
- [x] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Comment by liubog2008** [comment]
@DanielZhangQD @handlerww PTAL

**Comment by DanielZhangQD** [comment]
@liubog2008 Please update the test result in the PR description, there is no e2e test for backup now.

File: cmd/backup-manager/app/backup/manager.go [hunk 1]
```diff
@@ -166,11 +159,10 @@ func (bm *Manager) performBackup(ctx context.Context, backup *v1alpha1.Backup, d
 	updatePathStatus := &controller.BackupUpdateStatus{
 		BackupPath: &backupFullPath,
 	}
-	err = bm.StatusUpdater.Update(backup, &v1alpha1.BackupCondition{
+	if err := bm.StatusUpdater.Update(backup, &v1alpha1.BackupCondition{
```
Comment (DanielZhangQD) [inline cmd/backup-manager/app/backup/manager.go:162]: Is it better to move this block in the `db!=nil` branch in L175? Because if `db==nil`, there is nothing to prepare.

**Review by DanielZhangQD — COMMENTED** [review]
Rest LGTM

File: cmd/backup-manager/app/backup/manager.go (hunk 1 above)
Comment (liubog2008) [reply cmd/backup-manager/app/backup/manager.go:162]: If db == nil, `Prepare` condition should always be false?

Comment (DanielZhangQD) [reply cmd/backup-manager/app/backup/manager.go:162]: What about just skip setting this condition?

Comment (liubog2008) [reply cmd/backup-manager/app/backup/manager.go:162]: What means if `Prepare` condition is true? A prepare process is running or is finished ?

Comment (DanielZhangQD) [reply cmd/backup-manager/app/backup/manager.go:162]: Let's take it as the preparation process is running.

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Review by csuzhangxc — APPROVED** [review]
LGTM

**Comment by liubog2008** [comment]
- [x] Backup with BR with spec.from configured
- [x] Backup with BR without spec.from configured
- [x] Backup with Dumpling
